packages:
  - '.'
  - 'example'

onlyBuiltDependencies:
  - esbuild
  - lefthook
  - sharp

overrides:
  '@babel/generator': 8.0.0-rc.2
  '@babel/helper-string-parser': 8.0.0-rc.2
  '@babel/helper-validator-identifier': 8.0.0-rc.2
  '@babel/parser': 8.0.0-rc.2
  '@babel/types': 8.0.0-rc.2
  ast-kit: 3.0.0-beta.1
