'use client';

import {
  type ComponentType,
  type ForwardedRef,
  type ForwardRefExoticComponent,
  forwardRef,
  type LazyExoticComponent,
  lazy,
  type ReactNode,
  type RefAttributes,
  Suspense,
} from 'react';
import type { IconProps } from '../utils';

// `src` is type-checked without Node's global types, so declare only what the
// development check reads. Bundlers replace `process.env.NODE_ENV` with a
// string literal; where nothing replaced it and there is no `process`
// global, reading it throws, which warnInDevelopment() treats as production.
declare const process: { readonly env: { readonly NODE_ENV?: string } };

/**
 * Props every dynamic icon component accepts besides its identifier. `V` is
 * the category's variant union (e.g. `ChainVariant`).
 */
export interface DynamicIconProps<V extends string = 'colored' | 'mono'>
  extends Omit<IconProps, 'ref'> {
  /**
   * Icon variant: `'colored'` (the default), `'mono'`, or a variant suffix
   * the category ships (`'Circle'`, `'Square'`, …). An icon that lacks the
   * requested variant renders `fallback`.
   */
  variant?: V | undefined;
  /** Rendered while loading, when the identifier or variant is not recognized, or when the icon fails to load. */
  fallback?: ReactNode;
}

/** A dynamic icon component: props `P`, plus a `ref` to the `<svg>`. */
export type DynamicIconComponent<P extends DynamicIconProps<string>> =
  ForwardRefExoticComponent<P & RefAttributes<SVGSVGElement>>;

/** Lazy import of one icon module, keyed by export name. */
export type IconImports = Readonly<
  Record<string, () => Promise<Readonly<Record<string, unknown>>>>
>;

export interface DynamicIconConfig<P extends DynamicIconProps<string>> {
  /** Component name shown in React DevTools and in warnings (e.g. `'ChainIcon'`). */
  readonly displayName: string;
  /**
   * Maps the props to the export name of the icon's default variant (e.g.
   * `'Ethereum'`), or `undefined` if the identifier is not recognized.
   */
  readonly resolve: (props: P) => string | undefined;
  /** Per-icon lazy import map for the category (generated by the icon pipeline). */
  readonly imports: IconImports;
  /**
   * Variant suffixes `variant` accepts besides `'colored'` and `'mono'`
   * (generated by the icon pipeline).
   */
  readonly variants: readonly string[];
  /** Props that identify the icon; they are not forwarded to the `<svg>`. */
  readonly identifiers: readonly (keyof P & string)[];
}

/** An icon component as the icon modules export it. */
type IconComponent = ComponentType<
  Omit<IconProps, 'ref'> & RefAttributes<SVGSVGElement>
>;

/** What the lazily loaded component of an export name renders. */
interface LoadedProps {
  readonly iconProps: Omit<IconProps, 'ref'>;
  readonly iconRef: ForwardedRef<SVGSVGElement>;
  readonly fallback: ReactNode;
}

type LoadedComponent = LazyExoticComponent<ComponentType<LoadedProps>>;

/** A resolved icon: its export name and the import of its module. */
interface Resolved {
  readonly exportName: string;
  readonly importIcon: () => Promise<Readonly<Record<string, unknown>>>;
}

/** Icon modules export forwardRef components (see createIcon). */
function isIconComponent(value: unknown): value is IconComponent {
  return (
    typeof value === 'object' &&
    value !== null &&
    '$$typeof' in value &&
    value.$$typeof === Symbol.for('react.forward_ref')
  );
}

const warned: Set<string> = /* @__PURE__ */ new Set<string>();

/** A warning: its dedupe key, its message, and extra values to log. */
type Warning = readonly [key: string, message: string, ...details: unknown[]];

/**
 * Logs a warning once per key in development builds. The warning is built by
 * `describe` only inside the `process.env.NODE_ENV` check, so once a bundler
 * (Vite, webpack, Next.js, esbuild, …) replaces it with `"production"`, the
 * whole body is dead code and minifiers drop it with the messages.
 */
function warnInDevelopment(describe: () => Warning): void {
  try {
    if (process.env.NODE_ENV !== 'production') {
      const [key, message, ...details] = describe();
      if (!warned.has(key)) {
        warned.add(key);
        // biome-ignore lint/suspicious/noConsole: intentional development warning
        console.warn(`[react-web3-icons] ${message}`, ...details);
      }
    }
  } catch {
    // Nothing replaced process.env.NODE_ENV and there is no `process`
    // global: an unknown environment, so stay quiet.
  }
}

/**
 * The export-name suffix a `variant` selects: `'colored'` (or no variant)
 * → `''`, `'mono'` → `'Mono'`, one of the category's `variants` (`'Circle'`,
 * …) → itself; anything else → `undefined`.
 *
 * `'mono'` always selects the `Mono` export: when an icon had none it would
 * render `fallback` like any other missing variant, never the colored
 * artwork. The generator requires a `Mono` export for every lookup target,
 * so this does not happen for the shipped icons.
 */
export function variantSuffix(
  variant: unknown,
  variants: readonly string[],
): string | undefined {
  if (variant === undefined || variant === null || variant === 'colored') {
    return '';
  }
  if (variant === 'mono') {
    return 'Mono';
  }
  return typeof variant === 'string' && variants.includes(variant)
    ? variant
    : undefined;
}

function describeValue(value: unknown): string {
  return typeof value === 'string' ? JSON.stringify(value) : String(value);
}

function Failed({ fallback }: LoadedProps) {
  return <>{fallback}</>;
}

/** Renders a loaded icon with the props and ref of the dynamic component. */
function loaded(Icon: IconComponent): ComponentType<LoadedProps> {
  return function LoadedIcon({ iconProps, iconRef }: LoadedProps) {
    return <Icon {...iconProps} ref={iconRef} />;
  };
}

/**
 * Creates a dynamic icon component that lazily loads exactly one icon module
 * per resolved name, so rendering a single icon downloads a per-icon chunk
 * instead of the whole category bundle.
 *
 * `fallback` renders while the chunk loads, when the identifier or the
 * variant is not recognized, when the icon lacks the requested variant, and
 * when the chunk fails to load; a failed load is retried the next time the
 * component renders. The `ref` reaches the icon's `<svg>`.
 */
export function createDynamicIcon<P extends DynamicIconProps<string>>(
  config: DynamicIconConfig<P>,
): DynamicIconComponent<P>;
export function createDynamicIcon(
  config: DynamicIconConfig<DynamicIconProps<string>>,
): DynamicIconComponent<DynamicIconProps<string>> {
  const { displayName, resolve, imports, variants, identifiers } = config;
  const notForwarded = [...identifiers, 'variant', 'fallback'];
  const cache = new Map<string, LoadedComponent>();

  /** The lazy component of an icon of the import map. */
  function load({ exportName, importIcon }: Resolved): LoadedComponent {
    const cached = cache.get(exportName);
    if (cached) {
      return cached;
    }
    const component: LoadedComponent = lazy(() =>
      importIcon().then(
        mod => {
          const icon = mod[exportName];
          if (isIconComponent(icon)) {
            return { default: loaded(icon) };
          }
          // A chunk without the export (e.g. deploy skew) is a failed load
          // too: forget it so that the next render imports again.
          cache.delete(exportName);
          warnInDevelopment(() => [
            `${exportName} missing`,
            `${displayName}: the chunk of icon "${exportName}" does not export it; rendering the fallback until a later render retries.`,
          ]);
          return { default: Failed };
        },
        (error: unknown) => {
          // Forget the failed load so that the next render imports again.
          cache.delete(exportName);
          warnInDevelopment(() => [
            `${exportName} failed`,
            `${displayName}: loading icon "${exportName}" failed; rendering the fallback until a later render retries.`,
            error,
          ]);
          return { default: Failed };
        },
      ),
    );
    cache.set(exportName, component);
    return component;
  }

  /** The icon to render, or undefined (after a development warning). */
  function resolveIcon(props: DynamicIconProps<string>): Resolved | undefined {
    const target = resolve(props);
    if (target === undefined) {
      warnInDevelopment(() => {
        const input = identifiers
          .map(key => `${key}=${describeValue(Reflect.get(props, key))}`)
          .join(', ');
        return [
          `${displayName} ${input}`,
          `${displayName}: no icon for ${input}; rendering the fallback.`,
        ];
      });
      return undefined;
    }
    const { variant } = props;
    const suffix = variantSuffix(variant, variants);
    if (suffix === undefined) {
      warnInDevelopment(() => {
        const expected = ['colored', 'mono', ...variants]
          .map(v => JSON.stringify(v))
          .join(', ');
        return [
          `${displayName} variant=${describeValue(variant)}`,
          `${displayName}: unknown variant ${describeValue(variant)} (expected one of ${expected}); rendering the fallback.`,
        ];
      });
      return undefined;
    }
    const exportName = target + suffix;
    const importIcon = Object.hasOwn(imports, exportName)
      ? imports[exportName]
      : undefined;
    if (importIcon === undefined) {
      warnInDevelopment(() => [
        `${displayName} ${exportName}`,
        `${displayName}: ${target} has no ${describeValue(variant ?? 'colored')} variant; rendering the fallback.`,
      ]);
      return undefined;
    }
    return { exportName, importIcon };
  }

  const DynamicIcon = forwardRef<SVGSVGElement, DynamicIconProps<string>>(
    (props, ref) => {
      const { fallback = null } = props;
      const icon = resolveIcon(props);
      if (icon === undefined) {
        return <>{fallback}</>;
      }
      const Loaded = load(icon);
      const iconProps = { ...props };
      for (const key of notForwarded) {
        Reflect.deleteProperty(iconProps, key);
      }
      return (
        <Suspense fallback={fallback}>
          <Loaded iconProps={iconProps} iconRef={ref} fallback={fallback} />
        </Suspense>
      );
    },
  );
  DynamicIcon.displayName = displayName;
  return DynamicIcon;
}
