// Auto-generated by scripts/build-icons/cli.mjs — do not edit manually.
// Regenerate: pnpm run generate-icons
// biome-ignore-all lint/style/useNamingConvention: keys are icon export names (PascalCase)

/** Per-icon lazy import map for the bridge category. */
export const bridgeImports: Record<
  string,
  () => Promise<Record<string, unknown>>
> = {
  Across: () => import('../../bridge/Across'),
  AcrossMono: () => import('../../bridge/Across'),
  Axelar: () => import('../../bridge/Axelar'),
  AxelarMono: () => import('../../bridge/Axelar'),
  DeBridge: () => import('../../bridge/DeBridge'),
  DeBridgeMono: () => import('../../bridge/DeBridge'),
  HopProtocol: () => import('../../bridge/HopProtocol'),
  HopProtocolMono: () => import('../../bridge/HopProtocol'),
  LayerZero: () => import('../../bridge/LayerZero'),
  LayerZeroMono: () => import('../../bridge/LayerZero'),
  Orbiter: () => import('../../bridge/Orbiter'),
  OrbiterMono: () => import('../../bridge/Orbiter'),
  Socket: () => import('../../bridge/Socket'),
  SocketMono: () => import('../../bridge/Socket'),
  Stargate: () => import('../../bridge/Stargate'),
  StargateMono: () => import('../../bridge/Stargate'),
  Synapse: () => import('../../bridge/Synapse'),
  SynapseMono: () => import('../../bridge/Synapse'),
  Wormhole: () => import('../../bridge/Wormhole'),
  WormholeMono: () => import('../../bridge/Wormhole'),
};
