// Auto-generated by scripts/build-icons/cli.ts — do not edit manually.
// Regenerate: pnpm run generate-icons
// biome-ignore-all lint/style/useNamingConvention: keys are icon export names (PascalCase)

/**
 * Per-icon lazy import map for the bridge category: every export
 * `<BridgeIcon>` can render (a lookup target plus a variant suffix),
 * and nothing else.
 */
export const bridgeImports: Record<
  string,
  () => Promise<Record<string, unknown>>
> = {
  Across: () => import('../../bridge/Across'),
  AcrossMono: () => import('../../bridge/Across'),
  Axelar: () => import('../../bridge/Axelar'),
  AxelarMono: () => import('../../bridge/Axelar'),
  DeBridge: () => import('../../bridge/DeBridge'),
  DeBridgeMono: () => import('../../bridge/DeBridge'),
  HopProtocol: () => import('../../bridge/HopProtocol'),
  HopProtocolMono: () => import('../../bridge/HopProtocol'),
  LayerZero: () => import('../../bridge/LayerZero'),
  LayerZeroMono: () => import('../../bridge/LayerZero'),
  Orbiter: () => import('../../bridge/Orbiter'),
  OrbiterInverted: () => import('../../bridge/Orbiter'),
  OrbiterMono: () => import('../../bridge/Orbiter'),
  Socket: () => import('../../bridge/Socket'),
  SocketMono: () => import('../../bridge/Socket'),
  Stargate: () => import('../../bridge/Stargate'),
  StargateMono: () => import('../../bridge/Stargate'),
  Synapse: () => import('../../bridge/Synapse'),
  SynapseMono: () => import('../../bridge/Synapse'),
  Wormhole: () => import('../../bridge/Wormhole'),
  WormholeMono: () => import('../../bridge/Wormhole'),
};

/**
 * Variant suffixes `<BridgeIcon variant>` accepts besides `'colored'`
 * and `'mono'`: every one that some bridge icon ships.
 */
export const bridgeVariants: readonly string[] = ['Inverted'];

/**
 * `variant` of `<BridgeIcon>`: `'colored'` (the default) and `'mono'`,
 * plus every variant suffix some bridge icon ships. An icon without
 * the requested variant renders `fallback`.
 */
export type BridgeVariant = 'colored' | 'mono' | 'Inverted';
