// Auto-generated by scripts/build-icons/cli.ts — do not edit manually.
// Regenerate: pnpm run generate-icons
// biome-ignore-all lint/style/useNamingConvention: keys are icon export names (PascalCase)

/**
 * Per-icon lazy import map for the DEX category: every export
 * `<DexIcon>` can render (a lookup target plus a variant suffix),
 * and nothing else.
 */
export const dexImports: Record<
  string,
  () => Promise<Record<string, unknown>>
> = {
  Aerodrome: () => import('../../dex/Aerodrome'),
  AerodromeMono: () => import('../../dex/Aerodrome'),
  Camelot: () => import('../../dex/Camelot'),
  CamelotMono: () => import('../../dex/Camelot'),
  CowProtocol: () => import('../../dex/CowProtocol'),
  CowProtocolMono: () => import('../../dex/CowProtocol'),
  Dydx: () => import('../../dex/Dydx'),
  DydxMono: () => import('../../dex/Dydx'),
  DydxSquare: () => import('../../dex/Dydx'),
  DydxSquareMono: () => import('../../dex/Dydx'),
  Ekubo: () => import('../../dex/Ekubo'),
  EkuboMono: () => import('../../dex/Ekubo'),
  Fluid: () => import('../../dex/Fluid'),
  FluidMono: () => import('../../dex/Fluid'),
  Hyperliquid: () => import('../../dex/Hyperliquid'),
  HyperliquidMono: () => import('../../dex/Hyperliquid'),
  Jupiter: () => import('../../dex/Jupiter'),
  JupiterCircle: () => import('../../dex/Jupiter'),
  JupiterCircleMono: () => import('../../dex/Jupiter'),
  JupiterMono: () => import('../../dex/Jupiter'),
  Meteora: () => import('../../dex/Meteora'),
  MeteoraMono: () => import('../../dex/Meteora'),
  Oneinch: () => import('../../dex/Oneinch'),
  OneinchMono: () => import('../../dex/Oneinch'),
  Orca: () => import('../../dex/Orca'),
  OrcaMono: () => import('../../dex/Orca'),
  Osmosis: () => import('../../dex/Osmosis'),
  OsmosisMono: () => import('../../dex/Osmosis'),
  PancakeSwap: () => import('../../dex/PancakeSwap'),
  PancakeSwapMono: () => import('../../dex/PancakeSwap'),
  Raydium: () => import('../../dex/Raydium'),
  RaydiumMono: () => import('../../dex/Raydium'),
  SushiSwap: () => import('../../dex/SushiSwap'),
  SushiSwapMono: () => import('../../dex/SushiSwap'),
  Uniswap: () => import('../../dex/Uniswap'),
  UniswapMono: () => import('../../dex/Uniswap'),
  Velodrome: () => import('../../dex/Velodrome'),
  VelodromeMono: () => import('../../dex/Velodrome'),
  Velora: () => import('../../dex/Velora'),
  VeloraMono: () => import('../../dex/Velora'),
};

/**
 * Variant suffixes `<DexIcon variant>` accepts besides `'colored'`
 * and `'mono'`: every one that some DEX icon ships.
 */
export const dexVariants: readonly string[] = [
  'Circle',
  'CircleMono',
  'Square',
  'SquareMono',
];

/**
 * `variant` of `<DexIcon>`: `'colored'` (the default) and `'mono'`,
 * plus every variant suffix some DEX icon ships. An icon without
 * the requested variant renders `fallback`.
 */
export type DexVariant =
  | 'colored'
  | 'mono'
  | 'Circle'
  | 'CircleMono'
  | 'Square'
  | 'SquareMono';
