// Auto-generated by scripts/build-icons/cli.mjs — do not edit manually.
// Regenerate: pnpm run generate-icons
// biome-ignore-all lint/style/useNamingConvention: keys are icon export names (PascalCase)

/** Per-icon lazy import map for the dex category. */
export const dexImports: Record<
  string,
  () => Promise<Record<string, unknown>>
> = {
  Aerodrome: () => import('../../dex/Aerodrome'),
  AerodromeMono: () => import('../../dex/Aerodrome'),
  Camelot: () => import('../../dex/Camelot'),
  CamelotMono: () => import('../../dex/Camelot'),
  CowProtocol: () => import('../../dex/CowProtocol'),
  CowProtocolMono: () => import('../../dex/CowProtocol'),
  Dydx: () => import('../../dex/Dydx'),
  DydxMono: () => import('../../dex/Dydx'),
  DydxSquare: () => import('../../dex/Dydx'),
  DydxSquareMono: () => import('../../dex/Dydx'),
  Ekubo: () => import('../../dex/Ekubo'),
  EkuboMono: () => import('../../dex/Ekubo'),
  Hyperliquid: () => import('../../dex/Hyperliquid'),
  HyperliquidMono: () => import('../../dex/Hyperliquid'),
  Jupiter: () => import('../../dex/Jupiter'),
  JupiterMono: () => import('../../dex/Jupiter'),
  Odos: () => import('../../dex/Odos'),
  OdosMono: () => import('../../dex/Odos'),
  Oneinch: () => import('../../dex/Oneinch'),
  OneinchMono: () => import('../../dex/Oneinch'),
  Osmosis: () => import('../../dex/Osmosis'),
  OsmosisMono: () => import('../../dex/Osmosis'),
  PancakeSwap: () => import('../../dex/PancakeSwap'),
  PancakeSwapMono: () => import('../../dex/PancakeSwap'),
  ParaSwap: () => import('../../dex/ParaSwap'),
  ParaSwapMono: () => import('../../dex/ParaSwap'),
  Raydium: () => import('../../dex/Raydium'),
  RaydiumMono: () => import('../../dex/Raydium'),
  SushiSwap: () => import('../../dex/SushiSwap'),
  SushiSwapMono: () => import('../../dex/SushiSwap'),
  Uniswap: () => import('../../dex/Uniswap'),
  UniswapMono: () => import('../../dex/Uniswap'),
  Velodrome: () => import('../../dex/Velodrome'),
  VelodromeMono: () => import('../../dex/Velodrome'),
};
