// Auto-generated by scripts/build-icons/cli.ts — do not edit manually.
// Regenerate: pnpm run generate-icons
// biome-ignore-all lint/style/useNamingConvention: keys are icon export names (PascalCase)

/**
 * Per-icon lazy import map for the exchange category: every export
 * `<ExchangeIcon>` can render (a lookup target plus a variant suffix),
 * and nothing else.
 */
export const exchangeImports: Record<
  string,
  () => Promise<Record<string, unknown>>
> = {
  Binance: () => import('../../exchange/Binance'),
  BinanceMono: () => import('../../exchange/Binance'),
  Bitfinex: () => import('../../exchange/Bitfinex'),
  BitfinexMono: () => import('../../exchange/Bitfinex'),
  Bitget: () => import('../../exchange/Bitget'),
  BitgetMono: () => import('../../exchange/Bitget'),
  Bithumb: () => import('../../exchange/Bithumb'),
  BithumbMono: () => import('../../exchange/Bithumb'),
  Bitstamp: () => import('../../exchange/Bitstamp'),
  BitstampCircle: () => import('../../exchange/Bitstamp'),
  BitstampCircleMono: () => import('../../exchange/Bitstamp'),
  BitstampMono: () => import('../../exchange/Bitstamp'),
  Bybit: () => import('../../exchange/Bybit'),
  BybitInverted: () => import('../../exchange/Bybit'),
  BybitMono: () => import('../../exchange/Bybit'),
  Coinbase: () => import('../../exchange/Coinbase'),
  CoinbaseCircle: () => import('../../exchange/Coinbase'),
  CoinbaseCircleAlt: () => import('../../exchange/Coinbase'),
  CoinbaseCircleMono: () => import('../../exchange/Coinbase'),
  CoinbaseMono: () => import('../../exchange/Coinbase'),
  CryptoCom: () => import('../../exchange/CryptoCom'),
  CryptoComMono: () => import('../../exchange/CryptoCom'),
  Deribit: () => import('../../exchange/Deribit'),
  DeribitMono: () => import('../../exchange/Deribit'),
  Gate: () => import('../../exchange/Gate'),
  GateMono: () => import('../../exchange/Gate'),
  Gemini: () => import('../../exchange/Gemini'),
  GeminiMono: () => import('../../exchange/Gemini'),
  GeminiSquare: () => import('../../exchange/Gemini'),
  GeminiSquareMono: () => import('../../exchange/Gemini'),
  Htx: () => import('../../exchange/Htx'),
  HtxMono: () => import('../../exchange/Htx'),
  Kraken: () => import('../../exchange/Kraken'),
  KrakenMono: () => import('../../exchange/Kraken'),
  KuCoin: () => import('../../exchange/KuCoin'),
  KuCoinMono: () => import('../../exchange/KuCoin'),
  Mexc: () => import('../../exchange/Mexc'),
  MexcMono: () => import('../../exchange/Mexc'),
  Okx: () => import('../../exchange/Okx'),
  OkxMono: () => import('../../exchange/Okx'),
  Phemex: () => import('../../exchange/Phemex'),
  PhemexMono: () => import('../../exchange/Phemex'),
  Upbit: () => import('../../exchange/Upbit'),
  UpbitMono: () => import('../../exchange/Upbit'),
};

/**
 * Variant suffixes `<ExchangeIcon variant>` accepts besides `'colored'`
 * and `'mono'`: every one that some exchange icon ships.
 */
export const exchangeVariants: readonly string[] = [
  'Circle',
  'CircleAlt',
  'CircleMono',
  'Inverted',
  'Square',
  'SquareMono',
];

/**
 * `variant` of `<ExchangeIcon>`: `'colored'` (the default) and `'mono'`,
 * plus every variant suffix some exchange icon ships. An icon without
 * the requested variant renders `fallback`.
 */
export type ExchangeVariant =
  | 'colored'
  | 'mono'
  | 'Circle'
  | 'CircleAlt'
  | 'CircleMono'
  | 'Inverted'
  | 'Square'
  | 'SquareMono';
