// Auto-generated by scripts/build-icons/cli.mjs — do not edit manually.
// Regenerate: pnpm run generate-icons
// biome-ignore-all lint/style/useNamingConvention: keys are icon export names (PascalCase)

/** Per-icon lazy import map for the oracle category. */
export const oracleImports: Record<
  string,
  () => Promise<Record<string, unknown>>
> = {
  Api3: () => import('../../oracle/Api3'),
  Api3Mono: () => import('../../oracle/Api3'),
  Band: () => import('../../oracle/Band'),
  BandMono: () => import('../../oracle/Band'),
  Pyth: () => import('../../oracle/Pyth'),
  PythMono: () => import('../../oracle/Pyth'),
  RedStone: () => import('../../oracle/RedStone'),
  RedStoneMono: () => import('../../oracle/RedStone'),
};
