// Auto-generated by scripts/build-icons/cli.ts — do not edit manually.
// Regenerate: pnpm run generate-icons
// biome-ignore-all lint/style/useNamingConvention: keys are icon export names (PascalCase)

/**
 * Per-icon lazy import map for the oracle category: every export
 * `<OracleIcon>` can render (a lookup target plus a variant suffix),
 * and nothing else.
 */
export const oracleImports: Record<
  string,
  () => Promise<Record<string, unknown>>
> = {
  Api3: () => import('../../oracle/Api3'),
  Api3Mono: () => import('../../oracle/Api3'),
  Band: () => import('../../oracle/Band'),
  BandMono: () => import('../../oracle/Band'),
  Pyth: () => import('../../oracle/Pyth'),
  PythMono: () => import('../../oracle/Pyth'),
  RedStone: () => import('../../oracle/RedStone'),
  RedStoneMono: () => import('../../oracle/RedStone'),
};

/**
 * Variant suffixes `<OracleIcon variant>` accepts besides `'colored'`
 * and `'mono'`: every one that some oracle icon ships.
 */
export const oracleVariants: readonly string[] = [];

/**
 * `variant` of `<OracleIcon>`: `'colored'` (the default) and `'mono'`,
 * plus every variant suffix some oracle icon ships. An icon without
 * the requested variant renders `fallback`.
 */
export type OracleVariant = 'colored' | 'mono';
