// Auto-generated by scripts/build-icons/cli.ts — do not edit manually.
// Regenerate: pnpm run generate-icons
// biome-ignore-all lint/style/useNamingConvention: keys are icon export names (PascalCase)

/**
 * Per-icon lazy import map for the wallet category: every export
 * `<WalletIcon>` can render (a lookup target plus a variant suffix),
 * and nothing else.
 */
export const walletImports: Record<
  string,
  () => Promise<Record<string, unknown>>
> = {
  Backpack: () => import('../../wallet/Backpack'),
  BackpackMono: () => import('../../wallet/Backpack'),
  BitgetWallet: () => import('../../wallet/BitgetWallet'),
  BitgetWalletMono: () => import('../../wallet/BitgetWallet'),
  Brave: () => import('../../wallet/Brave'),
  BraveMono: () => import('../../wallet/Brave'),
  CoinbaseWallet: () => import('../../wallet/CoinbaseWallet'),
  CoinbaseWalletCircle: () => import('../../wallet/CoinbaseWallet'),
  CoinbaseWalletCircleMono: () => import('../../wallet/CoinbaseWallet'),
  CoinbaseWalletMono: () => import('../../wallet/CoinbaseWallet'),
  CoinbaseWalletSquare: () => import('../../wallet/CoinbaseWallet'),
  CoinbaseWalletSquareMono: () => import('../../wallet/CoinbaseWallet'),
  Daedalus: () => import('../../wallet/Daedalus'),
  DaedalusMono: () => import('../../wallet/Daedalus'),
  Enkrypt: () => import('../../wallet/Enkrypt'),
  EnkryptMono: () => import('../../wallet/Enkrypt'),
  Exodus: () => import('../../wallet/Exodus'),
  ExodusMono: () => import('../../wallet/Exodus'),
  ImToken: () => import('../../wallet/ImToken'),
  ImTokenMono: () => import('../../wallet/ImToken'),
  Keplr: () => import('../../wallet/Keplr'),
  KeplrMono: () => import('../../wallet/Keplr'),
  Ledger: () => import('../../wallet/Ledger'),
  LedgerMono: () => import('../../wallet/Ledger'),
  MetaMask: () => import('../../wallet/MetaMask'),
  MetaMaskAlt: () => import('../../wallet/MetaMask'),
  MetaMaskCircle: () => import('../../wallet/MetaMask'),
  MetaMaskCircleMono: () => import('../../wallet/MetaMask'),
  MetaMaskMono: () => import('../../wallet/MetaMask'),
  MetaMaskSquare: () => import('../../wallet/MetaMask'),
  MetaMaskSquareMono: () => import('../../wallet/MetaMask'),
  NamiWallet: () => import('../../wallet/NamiWallet'),
  NamiWalletMono: () => import('../../wallet/NamiWallet'),
  OkxWallet: () => import('../../wallet/OkxWallet'),
  OkxWalletMono: () => import('../../wallet/OkxWallet'),
  Petra: () => import('../../wallet/Petra'),
  PetraMono: () => import('../../wallet/Petra'),
  Phantom: () => import('../../wallet/Phantom'),
  PhantomCircle: () => import('../../wallet/Phantom'),
  PhantomCircleMono: () => import('../../wallet/Phantom'),
  PhantomMono: () => import('../../wallet/Phantom'),
  PhantomSquare: () => import('../../wallet/Phantom'),
  PhantomSquareMono: () => import('../../wallet/Phantom'),
  PhantomSymbolMono: () => import('../../wallet/Phantom'),
  PolkadotJs: () => import('../../wallet/PolkadotJs'),
  PolkadotJsMono: () => import('../../wallet/PolkadotJs'),
  Rabby: () => import('../../wallet/Rabby'),
  RabbyMono: () => import('../../wallet/Rabby'),
  Rainbow: () => import('../../wallet/Rainbow'),
  RainbowCircle: () => import('../../wallet/Rainbow'),
  RainbowCircleMono: () => import('../../wallet/Rainbow'),
  RainbowMono: () => import('../../wallet/Rainbow'),
  RainbowSquare: () => import('../../wallet/Rainbow'),
  RainbowSquareMono: () => import('../../wallet/Rainbow'),
  RainbowSymbol: () => import('../../wallet/Rainbow'),
  RainbowSymbolMono: () => import('../../wallet/Rainbow'),
  Ready: () => import('../../wallet/Ready'),
  ReadyMono: () => import('../../wallet/Ready'),
  Safe: () => import('../../wallet/Safe'),
  SafeMono: () => import('../../wallet/Safe'),
  Solflare: () => import('../../wallet/Solflare'),
  SolflareMono: () => import('../../wallet/Solflare'),
  SubWallet: () => import('../../wallet/SubWallet'),
  SubWalletMono: () => import('../../wallet/SubWallet'),
  Tangem: () => import('../../wallet/Tangem'),
  TangemMono: () => import('../../wallet/Tangem'),
  Trezor: () => import('../../wallet/Trezor'),
  TrezorMono: () => import('../../wallet/Trezor'),
  TrustWallet: () => import('../../wallet/TrustWallet'),
  TrustWalletCircle: () => import('../../wallet/TrustWallet'),
  TrustWalletCircleMono: () => import('../../wallet/TrustWallet'),
  TrustWalletMono: () => import('../../wallet/TrustWallet'),
  TrustWalletSquare: () => import('../../wallet/TrustWallet'),
  TrustWalletSquareMono: () => import('../../wallet/TrustWallet'),
  UniswapWallet: () => import('../../wallet/UniswapWallet'),
  UniswapWalletMono: () => import('../../wallet/UniswapWallet'),
  WalletConnect: () => import('../../wallet/WalletConnect'),
  WalletConnectCircle: () => import('../../wallet/WalletConnect'),
  WalletConnectCircleMono: () => import('../../wallet/WalletConnect'),
  WalletConnectMono: () => import('../../wallet/WalletConnect'),
  WalletConnectSquare: () => import('../../wallet/WalletConnect'),
  WalletConnectSquareMono: () => import('../../wallet/WalletConnect'),
  Xverse: () => import('../../wallet/Xverse'),
  XverseMono: () => import('../../wallet/Xverse'),
  Yoroi: () => import('../../wallet/Yoroi'),
  YoroiMono: () => import('../../wallet/Yoroi'),
  Zerion: () => import('../../wallet/Zerion'),
  ZerionCircle: () => import('../../wallet/Zerion'),
  ZerionCircleMono: () => import('../../wallet/Zerion'),
  ZerionMono: () => import('../../wallet/Zerion'),
  ZerionSquare: () => import('../../wallet/Zerion'),
  ZerionSquareMono: () => import('../../wallet/Zerion'),
};

/**
 * Variant suffixes `<WalletIcon variant>` accepts besides `'colored'`
 * and `'mono'`: every one that some wallet icon ships.
 */
export const walletVariants: readonly string[] = [
  'Alt',
  'Circle',
  'CircleMono',
  'Square',
  'SquareMono',
  'Symbol',
  'SymbolMono',
];

/**
 * `variant` of `<WalletIcon>`: `'colored'` (the default) and `'mono'`,
 * plus every variant suffix some wallet icon ships. An icon without
 * the requested variant renders `fallback`.
 */
export type WalletVariant =
  | 'colored'
  | 'mono'
  | 'Alt'
  | 'Circle'
  | 'CircleMono'
  | 'Square'
  | 'SquareMono'
  | 'Symbol'
  | 'SymbolMono';
