// Auto-generated by scripts/build-icons/cli.ts from icons/<category>/<slug>.json
// — do not edit manually. Regenerate: pnpm run generate-icons

/** Icon category, mirroring the package subpaths. */
export type IconCategory =
  | 'bridge'
  | 'chain'
  | 'coin'
  | 'defi'
  | 'devtool'
  | 'dex'
  | 'domain'
  | 'exchange'
  | 'explorer'
  | 'marketplace'
  | 'node'
  | 'oracle'
  | 'portfolio'
  | 'storage'
  | 'tracker'
  | 'wallet';

/**
 * Export name of an icon component: the same union as `IconName` from
 * `react-web3-icons`, spelled out so that the manifest's types load
 * without the icon types and `@types/react`.
 */
export type IconManifestName =
  | 'Aave'
  | 'AaveMono'
  | 'Abstract'
  | 'AbstractMono'
  | 'Across'
  | 'AcrossMono'
  | 'Ada'
  | 'AdaCircle'
  | 'AdaCircleMono'
  | 'AdaMono'
  | 'Aerodrome'
  | 'AerodromeMono'
  | 'Alchemy'
  | 'AlchemyMono'
  | 'Algo'
  | 'AlgoCircle'
  | 'AlgoCircleMono'
  | 'AlgoMono'
  | 'Algorand'
  | 'AlgorandCircle'
  | 'AlgorandCircleMono'
  | 'AlgorandMono'
  | 'Ankr'
  | 'AnkrMono'
  | 'Api3'
  | 'Api3Mono'
  | 'Apt'
  | 'AptMono'
  | 'Aptos'
  | 'AptosMono'
  | 'Aragon'
  | 'AragonCircle'
  | 'AragonCircleMono'
  | 'AragonMono'
  | 'Arb'
  | 'ArbCircle'
  | 'ArbCircleMono'
  | 'ArbMono'
  | 'Arbiscan'
  | 'ArbiscanMono'
  | 'Arbitrum'
  | 'ArbitrumCircle'
  | 'ArbitrumCircleMono'
  | 'ArbitrumMono'
  | 'ArbitrumNova'
  | 'ArbitrumNovaFlat'
  | 'ArbitrumNovaFlatMono'
  | 'ArbitrumNovaMono'
  | 'ArbitrumOne'
  | 'ArbitrumOneFlat'
  | 'ArbitrumOneFlatMono'
  | 'ArbitrumOneMono'
  | 'ArbitrumSquare'
  | 'ArbitrumSquareMono'
  | 'Argent'
  | 'ArgentMono'
  | 'Arkham'
  | 'ArkhamMono'
  | 'Arweave'
  | 'ArweaveMono'
  | 'Astar'
  | 'AstarMono'
  | 'Astr'
  | 'AstrMono'
  | 'Atom'
  | 'AtomMono'
  | 'Avalanche'
  | 'AvalancheCircle'
  | 'AvalancheCircleMono'
  | 'AvalancheMono'
  | 'AvalancheSquare'
  | 'AvalancheSquareMono'
  | 'Avascan'
  | 'AvascanMono'
  | 'AvascanWordmark'
  | 'AvascanWordmarkMono'
  | 'Avax'
  | 'AvaxCircle'
  | 'AvaxCircleMono'
  | 'AvaxMono'
  | 'Axelar'
  | 'AxelarMono'
  | 'Babylon'
  | 'BabylonMono'
  | 'Backpack'
  | 'BackpackMono'
  | 'BackpackWallet'
  | 'BackpackWalletMono'
  | 'Balancer'
  | 'BalancerMono'
  | 'Band'
  | 'BandMono'
  | 'Base'
  | 'BaseCircle'
  | 'BaseCircleMono'
  | 'BaseMono'
  | 'BaseSquare'
  | 'BaseSquareMono'
  | 'Basescan'
  | 'BasescanInverted'
  | 'BasescanMono'
  | 'Bch'
  | 'BchMono'
  | 'Bera'
  | 'BeraCircle'
  | 'BeraCircleMono'
  | 'BeraMono'
  | 'Berachain'
  | 'BerachainCircle'
  | 'BerachainCircleMono'
  | 'BerachainMono'
  | 'Binance'
  | 'BinanceMono'
  | 'BinanceSmartChain'
  | 'BinanceSmartChainCircle'
  | 'BinanceSmartChainCircleMono'
  | 'BinanceSmartChainMono'
  | 'BinanceSmartChainSquare'
  | 'BinanceSmartChainSquareMono'
  | 'Bitcoin'
  | 'BitcoinCircle'
  | 'BitcoinCircleMono'
  | 'BitcoinMono'
  | 'Bitfinex'
  | 'BitfinexMono'
  | 'Bitget'
  | 'BitgetMono'
  | 'BitgetWallet'
  | 'BitgetWalletMono'
  | 'Bithumb'
  | 'BithumbMono'
  | 'Bitstamp'
  | 'BitstampCircle'
  | 'BitstampCircleMono'
  | 'BitstampMono'
  | 'Blast'
  | 'BlastCircle'
  | 'BlastCircleMono'
  | 'BlastMono'
  | 'Blastscan'
  | 'BlastscanLight'
  | 'BlastscanMono'
  | 'Blockscout'
  | 'BlockscoutMono'
  | 'Bnb'
  | 'BnbCircle'
  | 'BnbCircleMono'
  | 'BnbMono'
  | 'BnbSmartChain'
  | 'BnbSmartChainCircle'
  | 'BnbSmartChainCircleMono'
  | 'BnbSmartChainMono'
  | 'BnbSmartChainSquare'
  | 'BnbSmartChainSquareMono'
  | 'Brave'
  | 'BraveMono'
  | 'Bscscan'
  | 'BscscanInverted'
  | 'BscscanMono'
  | 'Btc'
  | 'BtcCircle'
  | 'BtcCircleMono'
  | 'BtcMono'
  | 'Busd'
  | 'BusdMono'
  | 'Bybit'
  | 'BybitInverted'
  | 'BybitMono'
  | 'Cactus'
  | 'CactusMono'
  | 'Cake'
  | 'CakeMono'
  | 'Camelot'
  | 'CamelotMono'
  | 'Cardano'
  | 'CardanoCircle'
  | 'CardanoCircleMono'
  | 'CardanoMono'
  | 'Celestia'
  | 'CelestiaMono'
  | 'Celo'
  | 'CeloMono'
  | 'Celoscan'
  | 'CeloscanMono'
  | 'CeloscanSquare'
  | 'CeloscanSquareMono'
  | 'Chainlink'
  | 'ChainlinkMono'
  | 'Chainstack'
  | 'ChainstackMono'
  | 'CoinGecko'
  | 'CoinGeckoMono'
  | 'CoinLedger'
  | 'CoinLedgerMono'
  | 'CoinMarketCap'
  | 'CoinMarketCapCircle'
  | 'CoinMarketCapCircleMono'
  | 'CoinMarketCapMono'
  | 'Coinbase'
  | 'CoinbaseCircle'
  | 'CoinbaseCircleAlt'
  | 'CoinbaseCircleMono'
  | 'CoinbaseMono'
  | 'CoinbaseWallet'
  | 'CoinbaseWalletCircle'
  | 'CoinbaseWalletCircleMono'
  | 'CoinbaseWalletMono'
  | 'CoinbaseWalletSquare'
  | 'CoinbaseWalletSquareMono'
  | 'Coinpanda'
  | 'CoinpandaCircle'
  | 'CoinpandaCircleMono'
  | 'CoinpandaMono'
  | 'CoinpandaSquare'
  | 'CoinpandaSquareMono'
  | 'CollabLand'
  | 'CollabLandMono'
  | 'Compound'
  | 'CompoundMono'
  | 'Convex'
  | 'ConvexMono'
  | 'CosmosHub'
  | 'CosmosHubMono'
  | 'CowProtocol'
  | 'CowProtocolMono'
  | 'Cro'
  | 'CroMono'
  | 'Cronos'
  | 'CronosMono'
  | 'Crv'
  | 'CrvMono'
  | 'CryptoCom'
  | 'CryptoComMono'
  | 'Daedalus'
  | 'DaedalusMono'
  | 'DaedalusWallet'
  | 'DaedalusWalletMono'
  | 'Dai'
  | 'DaiCircle'
  | 'DaiCircleMono'
  | 'DaiMono'
  | 'Data'
  | 'DataMono'
  | 'DataNetwork'
  | 'DataNetworkMono'
  | 'DataNetworkSquare'
  | 'DataNetworkSquareMono'
  | 'DataSquare'
  | 'DataSquareMono'
  | 'DeBank'
  | 'DeBankMono'
  | 'DeBridge'
  | 'DeBridgeMono'
  | 'DefiLlama'
  | 'DefiLlamaMono'
  | 'Deribit'
  | 'DeribitMono'
  | 'DexScreener'
  | 'DexScreenerMono'
  | 'DexScreenerSymbolMono'
  | 'Doge'
  | 'DogeCircle'
  | 'DogeCircleMono'
  | 'DogeMono'
  | 'Dot'
  | 'DotMono'
  | 'Drpc'
  | 'DrpcMono'
  | 'Dune'
  | 'DuneMono'
  | 'DuneSquare'
  | 'DuneSquareMono'
  | 'Dydx'
  | 'DydxInverted'
  | 'DydxMono'
  | 'DydxSquare'
  | 'DydxSquareMono'
  | 'Eclipse'
  | 'EclipseMono'
  | 'Eigen'
  | 'EigenLayer'
  | 'EigenLayerMono'
  | 'EigenMono'
  | 'Ekubo'
  | 'EkuboMono'
  | 'Ena'
  | 'EnaMono'
  | 'Enkrypt'
  | 'EnkryptMono'
  | 'Ens'
  | 'EnsCircle'
  | 'EnsCircleMono'
  | 'EnsMono'
  | 'Eth'
  | 'EthCircle'
  | 'EthCircleMono'
  | 'EthMono'
  | 'Ethena'
  | 'EthenaMono'
  | 'EtherFi'
  | 'EtherFiMono'
  | 'Ethereum'
  | 'EthereumCircle'
  | 'EthereumCircleMono'
  | 'EthereumMono'
  | 'EthereumSquare'
  | 'EthereumSquareMono'
  | 'EthersJs'
  | 'EthersJsMono'
  | 'Etherscan'
  | 'EtherscanInverted'
  | 'EtherscanMono'
  | 'Exodus'
  | 'ExodusMono'
  | 'Fantom'
  | 'FantomMono'
  | 'Fdusd'
  | 'FdusdMono'
  | 'Fet'
  | 'FetMono'
  | 'Fil'
  | 'FilMono'
  | 'Flare'
  | 'FlareMono'
  | 'Flr'
  | 'FlrMono'
  | 'Fluid'
  | 'FluidMono'
  | 'Frax'
  | 'FraxMono'
  | 'Fraxtal'
  | 'FraxtalMono'
  | 'Ftm'
  | 'FtmMono'
  | 'Gate'
  | 'GateMono'
  | 'Gateio'
  | 'GateioMono'
  | 'Gemini'
  | 'GeminiMono'
  | 'GeminiSquare'
  | 'GeminiSquareMono'
  | 'Gmx'
  | 'GmxMono'
  | 'GnosisChain'
  | 'GnosisChainMono'
  | 'Gram'
  | 'GramCircle'
  | 'GramCircleMono'
  | 'GramMono'
  | 'Hardhat'
  | 'HardhatMono'
  | 'Hbar'
  | 'HbarMono'
  | 'Hedera'
  | 'HederaMono'
  | 'Helius'
  | 'HeliusMono'
  | 'HopProtocol'
  | 'HopProtocolMono'
  | 'Htx'
  | 'HtxInverted'
  | 'HtxMono'
  | 'Hype'
  | 'HypeMono'
  | 'Hyperliquid'
  | 'HyperliquidMono'
  | 'Icp'
  | 'IcpMono'
  | 'ImToken'
  | 'ImTokenMono'
  | 'Immutable'
  | 'ImmutableMono'
  | 'ImmutableX'
  | 'ImmutableXMono'
  | 'Infura'
  | 'InfuraMono'
  | 'Inj'
  | 'InjMono'
  | 'Injective'
  | 'InjectiveMono'
  | 'Ink'
  | 'InkMono'
  | 'Ipfs'
  | 'IpfsMono'
  | 'Jup'
  | 'JupCircle'
  | 'JupCircleMono'
  | 'JupMono'
  | 'Jupiter'
  | 'JupiterCircle'
  | 'JupiterCircleMono'
  | 'JupiterMono'
  | 'Kaia'
  | 'KaiaMono'
  | 'Kamino'
  | 'KaminoMono'
  | 'Kas'
  | 'KasMono'
  | 'Kava'
  | 'KavaCircle'
  | 'KavaCircleMono'
  | 'KavaMono'
  | 'Keplr'
  | 'KeplrMono'
  | 'Kraken'
  | 'KrakenMono'
  | 'KuCoin'
  | 'KuCoinMono'
  | 'Lace'
  | 'LaceMono'
  | 'LayerZero'
  | 'LayerZeroMono'
  | 'Ldo'
  | 'LdoCircle'
  | 'LdoCircleMono'
  | 'LdoMono'
  | 'Ledger'
  | 'LedgerMono'
  | 'Lido'
  | 'LidoMono'
  | 'Linea'
  | 'LineaMono'
  | 'Link'
  | 'LinkMono'
  | 'Liquity'
  | 'LiquityMono'
  | 'Looks'
  | 'LooksAlt'
  | 'LooksMono'
  | 'LooksRare'
  | 'LooksRareFlat'
  | 'LooksRareMono'
  | 'Ltc'
  | 'LtcMono'
  | 'MagicEden'
  | 'MagicEdenFlat'
  | 'MagicEdenMono'
  | 'MagicEdenWordmark'
  | 'MagicEdenWordmarkFlat'
  | 'MagicEdenWordmarkMono'
  | 'MakerDao'
  | 'MakerDaoMono'
  | 'MantaPacific'
  | 'MantaPacificMono'
  | 'Mantle'
  | 'MantleMono'
  | 'MantleSquare'
  | 'MantleSquareMono'
  | 'Maple'
  | 'MapleMono'
  | 'MetaMask'
  | 'MetaMaskAlt'
  | 'MetaMaskCircle'
  | 'MetaMaskCircleMono'
  | 'MetaMaskMono'
  | 'MetaMaskSquare'
  | 'MetaMaskSquareMono'
  | 'Meteora'
  | 'MeteoraMono'
  | 'Metis'
  | 'MetisMono'
  | 'Mexc'
  | 'MexcMono'
  | 'Mkr'
  | 'MkrMono'
  | 'Mnt'
  | 'MntMono'
  | 'MntSquare'
  | 'MntSquareMono'
  | 'Mode'
  | 'ModeCircle'
  | 'ModeCircleMono'
  | 'ModeMono'
  | 'Monad'
  | 'MonadCircle'
  | 'MonadCircleMono'
  | 'MonadMono'
  | 'Moralis'
  | 'MoralisMono'
  | 'Morpho'
  | 'MorphoMono'
  | 'NamiWallet'
  | 'NamiWalletMono'
  | 'Nansen'
  | 'NansenMono'
  | 'Near'
  | 'NearMono'
  | 'NftStorage'
  | 'NftStorageMono'
  | 'OKXWallet'
  | 'OKXWalletMono'
  | 'Odos'
  | 'OdosMono'
  | 'Okx'
  | 'OkxMono'
  | 'OkxWallet'
  | 'OkxWalletMono'
  | 'Ondo'
  | 'OndoMono'
  | 'Oneinch'
  | 'OneinchMono'
  | 'Op'
  | 'OpBnb'
  | 'OpBnbMono'
  | 'OpCircle'
  | 'OpCircleMono'
  | 'OpMono'
  | 'OpenSea'
  | 'OpenSeaAlt'
  | 'OpenSeaMono'
  | 'OpenSeaSymbol'
  | 'OpenSeaSymbolMono'
  | 'OpenZeppelin'
  | 'OpenZeppelinMono'
  | 'Optimism'
  | 'OptimismCircle'
  | 'OptimismCircleMono'
  | 'OptimismMono'
  | 'OptimismSquare'
  | 'OptimismSquareMono'
  | 'Orbiter'
  | 'OrbiterInverted'
  | 'OrbiterMono'
  | 'Orca'
  | 'OrcaMono'
  | 'Osmosis'
  | 'OsmosisMono'
  | 'PancakeSwap'
  | 'PancakeSwapMono'
  | 'ParaSwap'
  | 'ParaSwapMono'
  | 'Pendle'
  | 'PendleMono'
  | 'Pepe'
  | 'PepeMono'
  | 'Petra'
  | 'PetraMono'
  | 'Phantom'
  | 'PhantomCircle'
  | 'PhantomCircleMono'
  | 'PhantomMono'
  | 'PhantomSquare'
  | 'PhantomSquareMono'
  | 'PhantomSymbolMono'
  | 'PhantomWallet'
  | 'PhantomWalletCircle'
  | 'PhantomWalletCircleMono'
  | 'PhantomWalletMono'
  | 'PhantomWalletSquare'
  | 'PhantomWalletSquareMono'
  | 'PhantomWalletSymbolMono'
  | 'Phemex'
  | 'PhemexMono'
  | 'Pinata'
  | 'PinataMono'
  | 'Pol'
  | 'PolCircle'
  | 'PolCircleMono'
  | 'PolMono'
  | 'Polkadot'
  | 'PolkadotJs'
  | 'PolkadotJsMono'
  | 'PolkadotMono'
  | 'Polygon'
  | 'PolygonCircle'
  | 'PolygonCircleMono'
  | 'PolygonMono'
  | 'PolygonSquare'
  | 'PolygonSquareMono'
  | 'Privy'
  | 'PrivyMono'
  | 'Pyth'
  | 'PythMono'
  | 'QuickNode'
  | 'QuickNodeMono'
  | 'Rabby'
  | 'RabbyMono'
  | 'Rainbow'
  | 'RainbowCircle'
  | 'RainbowCircleMono'
  | 'RainbowMono'
  | 'RainbowSquare'
  | 'RainbowSquareMono'
  | 'RainbowSymbol'
  | 'RainbowSymbolMono'
  | 'RainbowWallet'
  | 'RainbowWalletCircle'
  | 'RainbowWalletCircleMono'
  | 'RainbowWalletMono'
  | 'RainbowWalletSquare'
  | 'RainbowWalletSquareMono'
  | 'RainbowWalletSymbol'
  | 'RainbowWalletSymbolMono'
  | 'Raydium'
  | 'RaydiumMono'
  | 'Ready'
  | 'ReadyMono'
  | 'RedStone'
  | 'RedStoneMono'
  | 'Remix'
  | 'RemixMono'
  | 'Render'
  | 'RenderMono'
  | 'RocketPool'
  | 'RocketPoolMono'
  | 'Ronin'
  | 'RoninCircle'
  | 'RoninCircleMono'
  | 'RoninMono'
  | 'Routescan'
  | 'RoutescanMono'
  | 'Safe'
  | 'SafeMono'
  | 'SafeProtocol'
  | 'SafeProtocolMono'
  | 'Scroll'
  | 'ScrollMono'
  | 'Sei'
  | 'SeiMono'
  | 'Shib'
  | 'ShibMono'
  | 'Sky'
  | 'SkyCircle'
  | 'SkyCircleMono'
  | 'SkyMono'
  | 'Socket'
  | 'SocketMono'
  | 'Sol'
  | 'SolCircle'
  | 'SolCircleMono'
  | 'SolMono'
  | 'Solana'
  | 'SolanaCircle'
  | 'SolanaCircleMono'
  | 'SolanaMono'
  | 'SolanaSquare'
  | 'SolanaSquareMono'
  | 'Solflare'
  | 'SolflareMono'
  | 'Solidity'
  | 'SolidityMono'
  | 'Solscan'
  | 'SolscanMono'
  | 'Soneium'
  | 'SoneiumMono'
  | 'Sonic'
  | 'SonicCircle'
  | 'SonicCircleMono'
  | 'SonicMono'
  | 'Spark'
  | 'SparkMono'
  | 'Stacks'
  | 'StacksMono'
  | 'Stargate'
  | 'StargateMono'
  | 'StarkNet'
  | 'StarkNetCircle'
  | 'StarkNetCircleMono'
  | 'StarkNetMono'
  | 'StarkNetSquare'
  | 'StarkNetSquareMono'
  | 'Starknet'
  | 'StarknetCircle'
  | 'StarknetCircleMono'
  | 'StarknetMono'
  | 'StarknetSquare'
  | 'StarknetSquareMono'
  | 'Stellar'
  | 'StellarMono'
  | 'Strk'
  | 'StrkCircle'
  | 'StrkCircleMono'
  | 'StrkMono'
  | 'StrkSquare'
  | 'StrkSquareMono'
  | 'Stx'
  | 'StxMono'
  | 'SubWallet'
  | 'SubWalletMono'
  | 'Sui'
  | 'SuiMono'
  | 'SushiSwap'
  | 'SushiSwapMono'
  | 'Synapse'
  | 'SynapseMono'
  | 'Synthetix'
  | 'SynthetixMono'
  | 'Taiko'
  | 'TaikoCircle'
  | 'TaikoCircleMono'
  | 'TaikoMono'
  | 'Tally'
  | 'TallyMono'
  | 'Tangem'
  | 'TangemMono'
  | 'Tao'
  | 'TaoMono'
  | 'Tenderly'
  | 'TenderlyMono'
  | 'Tensor'
  | 'TensorMono'
  | 'TheGraph'
  | 'TheGraphMono'
  | 'Thirdweb'
  | 'ThirdwebMono'
  | 'Tia'
  | 'TiaMono'
  | 'Ton'
  | 'TonMono'
  | 'Trezor'
  | 'TrezorMono'
  | 'Tron'
  | 'TronMono'
  | 'TrustWallet'
  | 'TrustWalletCircle'
  | 'TrustWalletCircleMono'
  | 'TrustWalletMono'
  | 'TrustWalletSquare'
  | 'TrustWalletSquareMono'
  | 'Trx'
  | 'TrxMono'
  | 'Uni'
  | 'UniMono'
  | 'Unichain'
  | 'UnichainMono'
  | 'Uniswap'
  | 'UniswapMono'
  | 'UniswapWallet'
  | 'UniswapWalletMono'
  | 'UnstoppableDomains'
  | 'UnstoppableDomainsMono'
  | 'Upbit'
  | 'UpbitMono'
  | 'Usdc'
  | 'UsdcCircle'
  | 'UsdcCircleMono'
  | 'UsdcMono'
  | 'Usde'
  | 'UsdeMono'
  | 'Usds'
  | 'UsdsMono'
  | 'Usdt'
  | 'UsdtCircle'
  | 'UsdtCircleMono'
  | 'UsdtMono'
  | 'Velodrome'
  | 'VelodromeMono'
  | 'Velora'
  | 'VeloraMono'
  | 'Venus'
  | 'VenusMono'
  | 'Vet'
  | 'VetMono'
  | 'Viem'
  | 'ViemMono'
  | 'Wagmi'
  | 'WagmiMono'
  | 'WalletConnect'
  | 'WalletConnectCircle'
  | 'WalletConnectCircleMono'
  | 'WalletConnectMono'
  | 'WalletConnectSquare'
  | 'WalletConnectSquareMono'
  | 'Walrus'
  | 'WalrusMono'
  | 'Web3Js'
  | 'Web3JsMono'
  | 'Wld'
  | 'WldMono'
  | 'WorldChain'
  | 'WorldChainMono'
  | 'Wormhole'
  | 'WormholeMono'
  | 'X2Y2'
  | 'X2Y2Mono'
  | 'Xlm'
  | 'XlmMono'
  | 'Xmr'
  | 'XmrMono'
  | 'Xrp'
  | 'XrpCircle'
  | 'XrpCircleMono'
  | 'XrpMono'
  | 'Xverse'
  | 'XverseMono'
  | 'Yearn'
  | 'YearnMono'
  | 'Yoroi'
  | 'YoroiMono'
  | 'YoroiWallet'
  | 'YoroiWalletMono'
  | 'Zapper'
  | 'ZapperMono'
  | 'Zec'
  | 'ZecMono'
  | 'Zerion'
  | 'ZerionCircle'
  | 'ZerionCircleMono'
  | 'ZerionMono'
  | 'ZerionSquare'
  | 'ZerionSquareMono'
  | 'ZkSync'
  | 'ZkSyncCircle'
  | 'ZkSyncCircleMono'
  | 'ZkSyncMono'
  | 'ZkSyncSquare'
  | 'ZkSyncSquareMono'
  | 'Zksync'
  | 'ZksyncCircle'
  | 'ZksyncCircleMono'
  | 'ZksyncMono'
  | 'ZksyncSquare'
  | 'ZksyncSquareMono'
  | 'Zora'
  | 'ZoraMono';

/** One exported icon component, as listed in the manifest. */
export interface IconManifestEntry {
  /** Export name of the component (e.g. `'Ethereum'`, `'EthereumMono'`). */
  readonly name: IconManifestName;
  /** Category subpath the component is exported from. */
  readonly category: IconCategory;
  /** EVM chain ID, present on chain icons registered in `CHAIN_ID_TO_NAME` (the primary one when it has several). */
  readonly chainId?: number;
  /** Lowercased slug, present when the icon is registered in a slug map (the primary one when it has several). */
  readonly slug?: string;
  /** Uppercase ticker symbol, present on coins registered in `TICKER_TO_COIN` (the primary one when it has several). */
  readonly ticker?: string;
  /** Set when the export is a deprecated alias kept for backward compatibility. */
  readonly deprecated?: true;
  /**
   * Variant suffixes of this icon, the colored default (`''`) and
   * `'Mono'` first, then each other suffix followed by its mono: each
   * `name + suffix` is an export of the same category. Deprecated variants are left out unless the icon itself is
   * deprecated. The exports of a longer name that a
   * `react-web3-icons/meta` map resolves to are left out too, as that
   * name's entry lists them (`'Nova'` is not a variant of `Arbitrum`:
   * `ArbitrumNova` has `['', 'Mono']`). Present on base entries
   * (re-exports such as `Eth` included, old names such as
   * `BinanceSmartChain` not) and on every entry `react-web3-icons/meta`
   * maps to.
   */
  readonly variants?: readonly string[];
  /** Extra lowercase search terms (e.g. `'btc'` on `Bitcoin`). Base entries only. */
  readonly aliases?: readonly string[];
  /**
   * Brand color as a `#rrggbb` hex: the most frequent non-neutral color of
   * the colored artwork (a heuristic; greys, near-black and near-white count
   * only when the artwork has nothing else, and artwork painted only in
   * SVG's default fill is `'#000000'`), or a curated override. An icon
   * that re-exports another icon's artwork (`Eth` → `Ethereum`) has that
   * icon's color. Present on the same entries as `variants`.
   */
  readonly brandColor?: string;
}

/**
 * Flat catalog of every exported icon component with its category and
 * runtime identifiers. Useful for building icon pickers, search indexes,
 * and documentation without importing the component bundles.
 */
export const ICON_MANIFEST: readonly IconManifestEntry[] = [
  {
    name: 'Across',
    category: 'bridge',
    slug: 'across',
    variants: ['', 'Mono'],
    brandColor: '#6cf9d8',
  },
  { name: 'AcrossMono', category: 'bridge' },
  {
    name: 'Axelar',
    category: 'bridge',
    slug: 'axelar',
    variants: ['', 'Mono'],
    brandColor: '#000000',
  },
  { name: 'AxelarMono', category: 'bridge' },
  {
    name: 'DeBridge',
    category: 'bridge',
    slug: 'debridge',
    variants: ['', 'Mono'],
    brandColor: '#d5d931',
  },
  { name: 'DeBridgeMono', category: 'bridge' },
  {
    name: 'HopProtocol',
    category: 'bridge',
    deprecated: true,
    variants: ['', 'Mono'],
    brandColor: '#b32eff',
  },
  { name: 'HopProtocolMono', category: 'bridge', deprecated: true },
  {
    name: 'LayerZero',
    category: 'bridge',
    slug: 'layerzero',
    variants: ['', 'Mono'],
    aliases: ['lz'],
    brandColor: '#000000',
  },
  { name: 'LayerZeroMono', category: 'bridge' },
  {
    name: 'Orbiter',
    category: 'bridge',
    slug: 'orbiter',
    variants: ['', 'Mono', 'Inverted'],
    brandColor: '#ef2f2d',
  },
  { name: 'OrbiterInverted', category: 'bridge' },
  { name: 'OrbiterMono', category: 'bridge' },
  {
    name: 'Socket',
    category: 'bridge',
    slug: 'socket',
    variants: ['', 'Mono'],
    brandColor: '#00ff79',
  },
  { name: 'SocketMono', category: 'bridge' },
  {
    name: 'Stargate',
    category: 'bridge',
    slug: 'stargate',
    variants: ['', 'Mono'],
    aliases: ['stg'],
    brandColor: '#999999',
  },
  { name: 'StargateMono', category: 'bridge' },
  {
    name: 'Synapse',
    category: 'bridge',
    slug: 'synapse',
    variants: ['', 'Mono'],
    brandColor: '#d24dff',
  },
  { name: 'SynapseMono', category: 'bridge' },
  {
    name: 'Wormhole',
    category: 'bridge',
    slug: 'wormhole',
    variants: ['', 'Mono'],
    brandColor: '#000000',
  },
  { name: 'WormholeMono', category: 'bridge' },
  {
    name: 'Abstract',
    category: 'chain',
    chainId: 2741,
    slug: 'abstract',
    variants: ['', 'Mono'],
    brandColor: '#00de73',
  },
  { name: 'AbstractMono', category: 'chain' },
  {
    name: 'Algorand',
    category: 'chain',
    slug: 'algorand',
    variants: ['', 'Mono', 'Circle', 'CircleMono'],
    brandColor: '#2d2df1',
  },
  { name: 'AlgorandCircle', category: 'chain' },
  { name: 'AlgorandCircleMono', category: 'chain' },
  { name: 'AlgorandMono', category: 'chain' },
  {
    name: 'Aptos',
    category: 'chain',
    slug: 'aptos',
    variants: ['', 'Mono'],
    brandColor: '#0f0e0b',
  },
  { name: 'AptosMono', category: 'chain' },
  {
    name: 'Arbitrum',
    category: 'chain',
    chainId: 42_161,
    slug: 'arbitrum',
    variants: ['', 'Mono', 'Circle', 'CircleMono', 'Square', 'SquareMono'],
    aliases: ['arb1'],
    brandColor: '#213147',
  },
  { name: 'ArbitrumCircle', category: 'chain' },
  { name: 'ArbitrumCircleMono', category: 'chain' },
  { name: 'ArbitrumMono', category: 'chain' },
  {
    name: 'ArbitrumNova',
    category: 'chain',
    chainId: 42_170,
    slug: 'arbitrum-nova',
    variants: ['', 'Mono'],
    brandColor: '#ff7700',
  },
  { name: 'ArbitrumNovaFlat', category: 'chain', deprecated: true },
  { name: 'ArbitrumNovaFlatMono', category: 'chain', deprecated: true },
  { name: 'ArbitrumNovaMono', category: 'chain' },
  {
    name: 'ArbitrumOne',
    category: 'chain',
    slug: 'arbitrum-one',
    variants: ['', 'Mono'],
    brandColor: '#1b4add',
  },
  { name: 'ArbitrumOneFlat', category: 'chain', deprecated: true },
  { name: 'ArbitrumOneFlatMono', category: 'chain', deprecated: true },
  { name: 'ArbitrumOneMono', category: 'chain' },
  { name: 'ArbitrumSquare', category: 'chain' },
  { name: 'ArbitrumSquareMono', category: 'chain' },
  {
    name: 'Astar',
    category: 'chain',
    chainId: 592,
    slug: 'astar',
    variants: ['', 'Mono'],
    brandColor: '#e6007a',
  },
  { name: 'AstarMono', category: 'chain' },
  {
    name: 'Avalanche',
    category: 'chain',
    chainId: 43_114,
    slug: 'avalanche',
    variants: ['', 'Mono', 'Circle', 'CircleMono', 'Square', 'SquareMono'],
    brandColor: '#e6212f',
  },
  { name: 'AvalancheCircle', category: 'chain' },
  { name: 'AvalancheCircleMono', category: 'chain' },
  { name: 'AvalancheMono', category: 'chain' },
  { name: 'AvalancheSquare', category: 'chain' },
  { name: 'AvalancheSquareMono', category: 'chain' },
  {
    name: 'Base',
    category: 'chain',
    chainId: 8453,
    slug: 'base',
    variants: ['', 'Mono', 'Circle', 'CircleMono', 'Square', 'SquareMono'],
    brandColor: '#0000ff',
  },
  { name: 'BaseCircle', category: 'chain' },
  { name: 'BaseCircleMono', category: 'chain' },
  { name: 'BaseMono', category: 'chain' },
  { name: 'BaseSquare', category: 'chain' },
  { name: 'BaseSquareMono', category: 'chain' },
  {
    name: 'Berachain',
    category: 'chain',
    chainId: 80_094,
    slug: 'berachain',
    variants: ['', 'Mono', 'Circle', 'CircleMono'],
    brandColor: '#2c1a16',
  },
  { name: 'BerachainCircle', category: 'chain' },
  { name: 'BerachainCircleMono', category: 'chain' },
  { name: 'BerachainMono', category: 'chain' },
  { name: 'BinanceSmartChain', category: 'chain', deprecated: true },
  { name: 'BinanceSmartChainCircle', category: 'chain', deprecated: true },
  { name: 'BinanceSmartChainCircleMono', category: 'chain', deprecated: true },
  { name: 'BinanceSmartChainMono', category: 'chain', deprecated: true },
  { name: 'BinanceSmartChainSquare', category: 'chain', deprecated: true },
  { name: 'BinanceSmartChainSquareMono', category: 'chain', deprecated: true },
  {
    name: 'Bitcoin',
    category: 'chain',
    slug: 'bitcoin',
    variants: ['', 'Mono', 'Circle', 'CircleMono'],
    aliases: ['btc'],
    brandColor: '#f7931a',
  },
  { name: 'BitcoinCircle', category: 'chain' },
  { name: 'BitcoinCircleMono', category: 'chain' },
  { name: 'BitcoinMono', category: 'chain' },
  {
    name: 'Blast',
    category: 'chain',
    chainId: 81_457,
    slug: 'blast',
    variants: ['', 'Mono', 'Circle', 'CircleMono'],
    brandColor: '#fcfc03',
  },
  { name: 'BlastCircle', category: 'chain' },
  { name: 'BlastCircleMono', category: 'chain' },
  { name: 'BlastMono', category: 'chain' },
  {
    name: 'BnbSmartChain',
    category: 'chain',
    chainId: 56,
    slug: 'bsc',
    variants: ['', 'Mono', 'Circle', 'CircleMono', 'Square', 'SquareMono'],
    aliases: ['bnb', 'bsc'],
    brandColor: '#f0b90b',
  },
  { name: 'BnbSmartChainCircle', category: 'chain' },
  { name: 'BnbSmartChainCircleMono', category: 'chain' },
  { name: 'BnbSmartChainMono', category: 'chain' },
  { name: 'BnbSmartChainSquare', category: 'chain' },
  { name: 'BnbSmartChainSquareMono', category: 'chain' },
  {
    name: 'Cardano',
    category: 'chain',
    slug: 'cardano',
    variants: ['', 'Mono', 'Circle', 'CircleMono'],
    brandColor: '#0033ad',
  },
  { name: 'CardanoCircle', category: 'chain' },
  { name: 'CardanoCircleMono', category: 'chain' },
  { name: 'CardanoMono', category: 'chain' },
  {
    name: 'Celestia',
    category: 'chain',
    slug: 'celestia',
    variants: ['', 'Mono'],
    brandColor: '#5640d1',
  },
  { name: 'CelestiaMono', category: 'chain' },
  {
    name: 'Celo',
    category: 'chain',
    chainId: 42_220,
    slug: 'celo',
    variants: ['', 'Mono'],
    brandColor: '#fcfe52',
  },
  { name: 'CeloMono', category: 'chain' },
  {
    name: 'CosmosHub',
    category: 'chain',
    slug: 'cosmos-hub',
    variants: ['', 'Mono'],
    brandColor: '#6f7390',
  },
  { name: 'CosmosHubMono', category: 'chain' },
  {
    name: 'Cronos',
    category: 'chain',
    chainId: 25,
    slug: 'cronos',
    variants: ['', 'Mono'],
    brandColor: '#4cdbff',
  },
  { name: 'CronosMono', category: 'chain' },
  {
    name: 'DataNetwork',
    category: 'chain',
    chainId: 1514,
    slug: 'data-network',
    variants: ['', 'Mono', 'Square', 'SquareMono'],
    aliases: ['story'],
    brandColor: '#1a1a1a',
  },
  { name: 'DataNetworkMono', category: 'chain' },
  { name: 'DataNetworkSquare', category: 'chain' },
  { name: 'DataNetworkSquareMono', category: 'chain' },
  {
    name: 'Eclipse',
    category: 'chain',
    slug: 'eclipse',
    variants: ['', 'Mono'],
    brandColor: '#a1fea0',
  },
  { name: 'EclipseMono', category: 'chain' },
  {
    name: 'Ethereum',
    category: 'chain',
    chainId: 1,
    slug: 'ethereum',
    variants: ['', 'Mono', 'Circle', 'CircleMono', 'Square', 'SquareMono'],
    brandColor: '#8c8c8c',
  },
  { name: 'EthereumCircle', category: 'chain' },
  { name: 'EthereumCircleMono', category: 'chain' },
  { name: 'EthereumMono', category: 'chain' },
  { name: 'EthereumSquare', category: 'chain' },
  { name: 'EthereumSquareMono', category: 'chain' },
  {
    name: 'Fantom',
    category: 'chain',
    deprecated: true,
    variants: ['', 'Mono'],
    brandColor: '#f37a29',
  },
  { name: 'FantomMono', category: 'chain', deprecated: true },
  {
    name: 'Fraxtal',
    category: 'chain',
    chainId: 252,
    slug: 'fraxtal',
    variants: ['', 'Mono'],
    brandColor: '#000000',
  },
  { name: 'FraxtalMono', category: 'chain' },
  {
    name: 'GnosisChain',
    category: 'chain',
    chainId: 100,
    slug: 'gnosis',
    variants: ['', 'Mono'],
    aliases: ['gno', 'gnosis'],
    brandColor: '#0d0d0d',
  },
  { name: 'GnosisChainMono', category: 'chain' },
  {
    name: 'Hedera',
    category: 'chain',
    chainId: 295,
    slug: 'hedera',
    variants: ['', 'Mono'],
    brandColor: '#000000',
  },
  { name: 'HederaMono', category: 'chain' },
  {
    name: 'Hyperliquid',
    category: 'chain',
    chainId: 999,
    slug: 'hyperliquid',
    variants: ['', 'Mono'],
    brandColor: '#97fce4',
  },
  { name: 'HyperliquidMono', category: 'chain' },
  {
    name: 'Immutable',
    category: 'chain',
    chainId: 13_371,
    slug: 'immutable',
    variants: ['', 'Mono'],
    brandColor: '#2b3038',
  },
  { name: 'ImmutableMono', category: 'chain' },
  { name: 'ImmutableX', category: 'chain', deprecated: true },
  { name: 'ImmutableXMono', category: 'chain', deprecated: true },
  {
    name: 'Injective',
    category: 'chain',
    chainId: 1776,
    slug: 'injective',
    variants: ['', 'Mono'],
    brandColor: '#4d3dff',
  },
  { name: 'InjectiveMono', category: 'chain' },
  {
    name: 'Ink',
    category: 'chain',
    chainId: 57_073,
    slug: 'ink',
    variants: ['', 'Mono'],
    brandColor: '#7132f5',
  },
  { name: 'InkMono', category: 'chain' },
  {
    name: 'Kaia',
    category: 'chain',
    chainId: 8217,
    slug: 'kaia',
    variants: ['', 'Mono'],
    aliases: ['klaytn'],
    brandColor: '#bff009',
  },
  { name: 'KaiaMono', category: 'chain' },
  {
    name: 'Kava',
    category: 'chain',
    chainId: 2222,
    slug: 'kava',
    variants: ['', 'Mono', 'Circle', 'CircleMono'],
    brandColor: '#ff433e',
  },
  { name: 'KavaCircle', category: 'chain' },
  { name: 'KavaCircleMono', category: 'chain' },
  { name: 'KavaMono', category: 'chain' },
  {
    name: 'Linea',
    category: 'chain',
    chainId: 59_144,
    slug: 'linea',
    variants: ['', 'Mono'],
    brandColor: '#000000',
  },
  { name: 'LineaMono', category: 'chain' },
  {
    name: 'MantaPacific',
    category: 'chain',
    chainId: 169,
    slug: 'manta',
    variants: ['', 'Mono'],
    aliases: ['manta'],
    brandColor: '#29ccb9',
  },
  { name: 'MantaPacificMono', category: 'chain' },
  {
    name: 'Mantle',
    category: 'chain',
    chainId: 5000,
    slug: 'mantle',
    variants: ['', 'Mono', 'Square', 'SquareMono'],
    brandColor: '#00ff93',
  },
  { name: 'MantleMono', category: 'chain' },
  { name: 'MantleSquare', category: 'chain' },
  { name: 'MantleSquareMono', category: 'chain' },
  {
    name: 'Metis',
    category: 'chain',
    chainId: 1088,
    slug: 'metis',
    variants: ['', 'Mono'],
    brandColor: '#00d2ff',
  },
  { name: 'MetisMono', category: 'chain' },
  {
    name: 'Mode',
    category: 'chain',
    chainId: 34_443,
    slug: 'mode',
    variants: ['', 'Mono', 'Circle', 'CircleMono'],
    brandColor: '#dffe00',
  },
  { name: 'ModeCircle', category: 'chain' },
  { name: 'ModeCircleMono', category: 'chain' },
  { name: 'ModeMono', category: 'chain' },
  {
    name: 'Monad',
    category: 'chain',
    chainId: 143,
    slug: 'monad',
    variants: ['', 'Mono', 'Circle', 'CircleMono'],
    aliases: ['mon'],
    brandColor: '#6e54ff',
  },
  { name: 'MonadCircle', category: 'chain' },
  { name: 'MonadCircleMono', category: 'chain' },
  { name: 'MonadMono', category: 'chain' },
  {
    name: 'Near',
    category: 'chain',
    slug: 'near',
    variants: ['', 'Mono'],
    brandColor: '#000000',
  },
  { name: 'NearMono', category: 'chain' },
  {
    name: 'OpBnb',
    category: 'chain',
    chainId: 204,
    slug: 'opbnb',
    variants: ['', 'Mono'],
    brandColor: '#f0b90b',
  },
  { name: 'OpBnbMono', category: 'chain' },
  {
    name: 'Optimism',
    category: 'chain',
    chainId: 10,
    slug: 'optimism',
    variants: ['', 'Mono', 'Circle', 'CircleMono', 'Square', 'SquareMono'],
    brandColor: '#ff0421',
  },
  { name: 'OptimismCircle', category: 'chain' },
  { name: 'OptimismCircleMono', category: 'chain' },
  { name: 'OptimismMono', category: 'chain' },
  { name: 'OptimismSquare', category: 'chain' },
  { name: 'OptimismSquareMono', category: 'chain' },
  {
    name: 'Polkadot',
    category: 'chain',
    slug: 'polkadot',
    variants: ['', 'Mono'],
    aliases: ['dot'],
    brandColor: '#171717',
  },
  { name: 'PolkadotMono', category: 'chain' },
  {
    name: 'Polygon',
    category: 'chain',
    chainId: 137,
    slug: 'polygon',
    variants: ['', 'Mono', 'Square', 'SquareMono', 'Circle', 'CircleMono'],
    aliases: ['matic'],
    brandColor: '#670de5',
  },
  { name: 'PolygonCircle', category: 'chain' },
  { name: 'PolygonCircleMono', category: 'chain' },
  { name: 'PolygonMono', category: 'chain' },
  { name: 'PolygonSquare', category: 'chain' },
  { name: 'PolygonSquareMono', category: 'chain' },
  {
    name: 'Ronin',
    category: 'chain',
    chainId: 2020,
    slug: 'ronin',
    variants: ['', 'Mono', 'Circle', 'CircleMono'],
    aliases: ['ron', 'axie'],
    brandColor: '#004de5',
  },
  { name: 'RoninCircle', category: 'chain' },
  { name: 'RoninCircleMono', category: 'chain' },
  { name: 'RoninMono', category: 'chain' },
  {
    name: 'Scroll',
    category: 'chain',
    chainId: 534_352,
    slug: 'scroll',
    variants: ['', 'Mono'],
    brandColor: '#0a0a0a',
  },
  { name: 'ScrollMono', category: 'chain' },
  {
    name: 'Sei',
    category: 'chain',
    chainId: 1329,
    slug: 'sei',
    variants: ['', 'Mono'],
    brandColor: '#600014',
  },
  { name: 'SeiMono', category: 'chain' },
  {
    name: 'Solana',
    category: 'chain',
    slug: 'solana',
    variants: ['', 'Mono', 'Circle', 'CircleMono', 'Square', 'SquareMono'],
    brandColor: '#9945ff',
  },
  { name: 'SolanaCircle', category: 'chain' },
  { name: 'SolanaCircleMono', category: 'chain' },
  { name: 'SolanaMono', category: 'chain' },
  { name: 'SolanaSquare', category: 'chain' },
  { name: 'SolanaSquareMono', category: 'chain' },
  {
    name: 'Soneium',
    category: 'chain',
    chainId: 1868,
    slug: 'soneium',
    variants: ['', 'Mono'],
    brandColor: '#000000',
  },
  { name: 'SoneiumMono', category: 'chain' },
  {
    name: 'Sonic',
    category: 'chain',
    chainId: 146,
    slug: 'sonic',
    variants: ['', 'Mono', 'Circle', 'CircleMono'],
    aliases: ['s', 'fantom', 'ftm'],
    brandColor: '#fac461',
  },
  { name: 'SonicCircle', category: 'chain' },
  { name: 'SonicCircleMono', category: 'chain' },
  { name: 'SonicMono', category: 'chain' },
  {
    name: 'Stacks',
    category: 'chain',
    slug: 'stacks',
    variants: ['', 'Mono'],
    brandColor: '#fc6432',
  },
  { name: 'StacksMono', category: 'chain' },
  { name: 'StarkNet', category: 'chain', deprecated: true },
  { name: 'StarkNetCircle', category: 'chain', deprecated: true },
  { name: 'StarkNetCircleMono', category: 'chain', deprecated: true },
  { name: 'StarkNetMono', category: 'chain', deprecated: true },
  { name: 'StarkNetSquare', category: 'chain', deprecated: true },
  { name: 'StarkNetSquareMono', category: 'chain', deprecated: true },
  {
    name: 'Starknet',
    category: 'chain',
    slug: 'starknet',
    variants: ['', 'Mono', 'Circle', 'CircleMono', 'Square', 'SquareMono'],
    brandColor: '#ec796b',
  },
  { name: 'StarknetCircle', category: 'chain' },
  { name: 'StarknetCircleMono', category: 'chain' },
  { name: 'StarknetMono', category: 'chain' },
  { name: 'StarknetSquare', category: 'chain' },
  { name: 'StarknetSquareMono', category: 'chain' },
  {
    name: 'Stellar',
    category: 'chain',
    slug: 'stellar',
    variants: ['', 'Mono'],
    brandColor: '#000000',
  },
  { name: 'StellarMono', category: 'chain' },
  {
    name: 'Sui',
    category: 'chain',
    slug: 'sui',
    variants: ['', 'Mono'],
    brandColor: '#298dff',
  },
  { name: 'SuiMono', category: 'chain' },
  {
    name: 'Taiko',
    category: 'chain',
    chainId: 167_000,
    slug: 'taiko',
    variants: ['', 'Mono', 'Circle', 'CircleMono'],
    brandColor: '#e81899',
  },
  { name: 'TaikoCircle', category: 'chain' },
  { name: 'TaikoCircleMono', category: 'chain' },
  { name: 'TaikoMono', category: 'chain' },
  {
    name: 'Ton',
    category: 'chain',
    slug: 'ton',
    variants: ['', 'Mono'],
    brandColor: '#0098ea',
  },
  { name: 'TonMono', category: 'chain' },
  {
    name: 'Tron',
    category: 'chain',
    slug: 'tron',
    variants: ['', 'Mono'],
    brandColor: '#ea0029',
  },
  { name: 'TronMono', category: 'chain' },
  {
    name: 'Unichain',
    category: 'chain',
    chainId: 130,
    slug: 'unichain',
    variants: ['', 'Mono'],
    brandColor: '#f50db4',
  },
  { name: 'UnichainMono', category: 'chain' },
  {
    name: 'WorldChain',
    category: 'chain',
    chainId: 480,
    slug: 'worldchain',
    variants: ['', 'Mono'],
    brandColor: '#000000',
  },
  { name: 'WorldChainMono', category: 'chain' },
  { name: 'ZkSync', category: 'chain', deprecated: true },
  { name: 'ZkSyncCircle', category: 'chain', deprecated: true },
  { name: 'ZkSyncCircleMono', category: 'chain', deprecated: true },
  { name: 'ZkSyncMono', category: 'chain', deprecated: true },
  { name: 'ZkSyncSquare', category: 'chain', deprecated: true },
  { name: 'ZkSyncSquareMono', category: 'chain', deprecated: true },
  {
    name: 'Zksync',
    category: 'chain',
    chainId: 324,
    slug: 'zksync',
    variants: ['', 'Mono', 'Circle', 'CircleMono', 'Square', 'SquareMono'],
    aliases: ['zk'],
    brandColor: '#11141a',
  },
  { name: 'ZksyncCircle', category: 'chain' },
  { name: 'ZksyncCircleMono', category: 'chain' },
  { name: 'ZksyncMono', category: 'chain' },
  { name: 'ZksyncSquare', category: 'chain' },
  { name: 'ZksyncSquareMono', category: 'chain' },
  {
    name: 'Zora',
    category: 'chain',
    chainId: 7_777_777,
    slug: 'zora',
    variants: ['', 'Mono'],
    brandColor: '#f2cefe',
  },
  { name: 'ZoraMono', category: 'chain' },
  {
    name: 'Ada',
    category: 'coin',
    ticker: 'ADA',
    variants: ['', 'Mono', 'Circle', 'CircleMono'],
    brandColor: '#0033ad',
  },
  { name: 'AdaCircle', category: 'coin' },
  { name: 'AdaCircleMono', category: 'coin' },
  { name: 'AdaMono', category: 'coin' },
  {
    name: 'Algo',
    category: 'coin',
    ticker: 'ALGO',
    variants: ['', 'Mono', 'Circle', 'CircleMono'],
    brandColor: '#2d2df1',
  },
  { name: 'AlgoCircle', category: 'coin' },
  { name: 'AlgoCircleMono', category: 'coin' },
  { name: 'AlgoMono', category: 'coin' },
  {
    name: 'Apt',
    category: 'coin',
    ticker: 'APT',
    variants: ['', 'Mono'],
    brandColor: '#0f0e0b',
  },
  { name: 'AptMono', category: 'coin' },
  {
    name: 'Arb',
    category: 'coin',
    ticker: 'ARB',
    variants: ['', 'Mono', 'Circle', 'CircleMono'],
    brandColor: '#213147',
  },
  { name: 'ArbCircle', category: 'coin' },
  { name: 'ArbCircleMono', category: 'coin' },
  { name: 'ArbMono', category: 'coin' },
  {
    name: 'Astr',
    category: 'coin',
    ticker: 'ASTR',
    variants: ['', 'Mono'],
    brandColor: '#e6007a',
  },
  { name: 'AstrMono', category: 'coin' },
  {
    name: 'Atom',
    category: 'coin',
    ticker: 'ATOM',
    variants: ['', 'Mono'],
    aliases: ['atom'],
    brandColor: '#6f7390',
  },
  { name: 'AtomMono', category: 'coin' },
  {
    name: 'Avax',
    category: 'coin',
    ticker: 'AVAX',
    variants: ['', 'Mono', 'Circle', 'CircleMono'],
    brandColor: '#e6212f',
  },
  { name: 'AvaxCircle', category: 'coin' },
  { name: 'AvaxCircleMono', category: 'coin' },
  { name: 'AvaxMono', category: 'coin' },
  {
    name: 'Bch',
    category: 'coin',
    ticker: 'BCH',
    variants: ['', 'Mono'],
    brandColor: '#0ac18e',
  },
  { name: 'BchMono', category: 'coin' },
  {
    name: 'Bera',
    category: 'coin',
    ticker: 'BERA',
    variants: ['', 'Mono', 'Circle', 'CircleMono'],
    brandColor: '#2c1a16',
  },
  { name: 'BeraCircle', category: 'coin' },
  { name: 'BeraCircleMono', category: 'coin' },
  { name: 'BeraMono', category: 'coin' },
  {
    name: 'Bnb',
    category: 'coin',
    ticker: 'BNB',
    variants: ['', 'Mono', 'Circle', 'CircleMono'],
    brandColor: '#f0b90b',
  },
  { name: 'BnbCircle', category: 'coin' },
  { name: 'BnbCircleMono', category: 'coin' },
  { name: 'BnbMono', category: 'coin' },
  {
    name: 'Btc',
    category: 'coin',
    ticker: 'BTC',
    variants: ['', 'Mono', 'Circle', 'CircleMono'],
    brandColor: '#f7931a',
  },
  { name: 'BtcCircle', category: 'coin' },
  { name: 'BtcCircleMono', category: 'coin' },
  { name: 'BtcMono', category: 'coin' },
  {
    name: 'Busd',
    category: 'coin',
    deprecated: true,
    variants: ['', 'Mono'],
    brandColor: '#f0b90b',
  },
  { name: 'BusdMono', category: 'coin', deprecated: true },
  {
    name: 'Cake',
    category: 'coin',
    ticker: 'CAKE',
    variants: ['', 'Mono'],
    brandColor: '#633001',
  },
  { name: 'CakeMono', category: 'coin' },
  {
    name: 'Celo',
    category: 'coin',
    ticker: 'CELO',
    variants: ['', 'Mono'],
    brandColor: '#fcfe52',
  },
  { name: 'CeloMono', category: 'coin' },
  {
    name: 'Cro',
    category: 'coin',
    ticker: 'CRO',
    variants: ['', 'Mono'],
    brandColor: '#4cdbff',
  },
  { name: 'CroMono', category: 'coin' },
  {
    name: 'Crv',
    category: 'coin',
    ticker: 'CRV',
    variants: ['', 'Mono'],
    brandColor: '#1cffdb',
  },
  { name: 'CrvMono', category: 'coin' },
  {
    name: 'Dai',
    category: 'coin',
    ticker: 'DAI',
    variants: ['', 'Mono', 'Circle', 'CircleMono'],
    brandColor: '#f5ac37',
  },
  { name: 'DaiCircle', category: 'coin' },
  { name: 'DaiCircleMono', category: 'coin' },
  { name: 'DaiMono', category: 'coin' },
  {
    name: 'Data',
    category: 'coin',
    ticker: 'DATA',
    variants: ['', 'Mono', 'Square', 'SquareMono'],
    brandColor: '#1a1a1a',
  },
  { name: 'DataMono', category: 'coin' },
  { name: 'DataSquare', category: 'coin' },
  { name: 'DataSquareMono', category: 'coin' },
  {
    name: 'Doge',
    category: 'coin',
    ticker: 'DOGE',
    variants: ['', 'Mono', 'Circle', 'CircleMono'],
    brandColor: '#a88f33',
  },
  { name: 'DogeCircle', category: 'coin' },
  { name: 'DogeCircleMono', category: 'coin' },
  { name: 'DogeMono', category: 'coin' },
  {
    name: 'Dot',
    category: 'coin',
    ticker: 'DOT',
    variants: ['', 'Mono'],
    brandColor: '#171717',
  },
  { name: 'DotMono', category: 'coin' },
  {
    name: 'Eigen',
    category: 'coin',
    ticker: 'EIGEN',
    variants: ['', 'Mono'],
    brandColor: '#1a0c6d',
  },
  { name: 'EigenMono', category: 'coin' },
  {
    name: 'Ena',
    category: 'coin',
    ticker: 'ENA',
    variants: ['', 'Mono'],
    brandColor: '#040404',
  },
  { name: 'EnaMono', category: 'coin' },
  {
    name: 'Eth',
    category: 'coin',
    ticker: 'ETH',
    variants: ['', 'Mono', 'Circle', 'CircleMono'],
    brandColor: '#8c8c8c',
  },
  { name: 'EthCircle', category: 'coin' },
  { name: 'EthCircleMono', category: 'coin' },
  { name: 'EthMono', category: 'coin' },
  {
    name: 'Fdusd',
    category: 'coin',
    ticker: 'FDUSD',
    variants: ['', 'Mono'],
    brandColor: '#02ec81',
  },
  { name: 'FdusdMono', category: 'coin' },
  {
    name: 'Fet',
    category: 'coin',
    ticker: 'FET',
    variants: ['', 'Mono'],
    brandColor: '#151a1a',
  },
  { name: 'FetMono', category: 'coin' },
  {
    name: 'Fil',
    category: 'coin',
    ticker: 'FIL',
    variants: ['', 'Mono'],
    brandColor: '#0090ff',
  },
  { name: 'FilMono', category: 'coin' },
  {
    name: 'Flare',
    category: 'coin',
    variants: ['', 'Mono'],
    brandColor: '#e62058',
  },
  { name: 'FlareMono', category: 'coin' },
  {
    name: 'Flr',
    category: 'coin',
    ticker: 'FLR',
    variants: ['', 'Mono'],
    brandColor: '#e62058',
  },
  { name: 'FlrMono', category: 'coin' },
  { name: 'Ftm', category: 'coin', deprecated: true },
  { name: 'FtmMono', category: 'coin', deprecated: true },
  {
    name: 'Gram',
    category: 'coin',
    ticker: 'GRAM',
    variants: ['', 'Mono', 'Circle', 'CircleMono'],
    brandColor: '#30a1f5',
  },
  { name: 'GramCircle', category: 'coin' },
  { name: 'GramCircleMono', category: 'coin' },
  { name: 'GramMono', category: 'coin' },
  {
    name: 'Hbar',
    category: 'coin',
    ticker: 'HBAR',
    variants: ['', 'Mono'],
    brandColor: '#000000',
  },
  { name: 'HbarMono', category: 'coin' },
  {
    name: 'Hype',
    category: 'coin',
    ticker: 'HYPE',
    variants: ['', 'Mono'],
    brandColor: '#97fce4',
  },
  { name: 'HypeMono', category: 'coin' },
  {
    name: 'Icp',
    category: 'coin',
    ticker: 'ICP',
    variants: ['', 'Mono'],
    brandColor: '#f15a24',
  },
  { name: 'IcpMono', category: 'coin' },
  {
    name: 'Inj',
    category: 'coin',
    ticker: 'INJ',
    variants: ['', 'Mono'],
    brandColor: '#4d3dff',
  },
  { name: 'InjMono', category: 'coin' },
  {
    name: 'Jup',
    category: 'coin',
    ticker: 'JUP',
    variants: ['', 'Mono', 'Circle', 'CircleMono'],
    brandColor: '#c7f284',
  },
  { name: 'JupCircle', category: 'coin' },
  { name: 'JupCircleMono', category: 'coin' },
  { name: 'JupMono', category: 'coin' },
  {
    name: 'Kaia',
    category: 'coin',
    ticker: 'KAIA',
    variants: ['', 'Mono'],
    brandColor: '#bff009',
  },
  { name: 'KaiaMono', category: 'coin' },
  {
    name: 'Kas',
    category: 'coin',
    ticker: 'KAS',
    variants: ['', 'Mono'],
    brandColor: '#6fc7ba',
  },
  { name: 'KasMono', category: 'coin' },
  {
    name: 'Kava',
    category: 'coin',
    ticker: 'KAVA',
    variants: ['', 'Mono', 'Circle', 'CircleMono'],
    brandColor: '#ff433e',
  },
  { name: 'KavaCircle', category: 'coin' },
  { name: 'KavaCircleMono', category: 'coin' },
  { name: 'KavaMono', category: 'coin' },
  {
    name: 'Ldo',
    category: 'coin',
    ticker: 'LDO',
    variants: ['', 'Mono', 'Circle', 'CircleMono'],
    brandColor: '#0085ff',
  },
  { name: 'LdoCircle', category: 'coin' },
  { name: 'LdoCircleMono', category: 'coin' },
  { name: 'LdoMono', category: 'coin' },
  {
    name: 'Link',
    category: 'coin',
    ticker: 'LINK',
    variants: ['', 'Mono'],
    brandColor: '#0847f7',
  },
  { name: 'LinkMono', category: 'coin' },
  {
    name: 'Looks',
    category: 'coin',
    ticker: 'LOOKS',
    variants: ['', 'Mono', 'Alt'],
    brandColor: '#0ce466',
  },
  { name: 'LooksAlt', category: 'coin' },
  { name: 'LooksMono', category: 'coin' },
  {
    name: 'Ltc',
    category: 'coin',
    ticker: 'LTC',
    variants: ['', 'Mono'],
    brandColor: '#345d9d',
  },
  { name: 'LtcMono', category: 'coin' },
  { name: 'Mkr', category: 'coin', deprecated: true },
  { name: 'MkrMono', category: 'coin', deprecated: true },
  {
    name: 'Mnt',
    category: 'coin',
    ticker: 'MNT',
    variants: ['', 'Mono', 'Square', 'SquareMono'],
    brandColor: '#00ff93',
  },
  { name: 'MntMono', category: 'coin' },
  { name: 'MntSquare', category: 'coin' },
  { name: 'MntSquareMono', category: 'coin' },
  {
    name: 'Monad',
    category: 'coin',
    ticker: 'MON',
    variants: ['', 'Mono', 'Circle', 'CircleMono'],
    brandColor: '#6e54ff',
  },
  { name: 'MonadCircle', category: 'coin' },
  { name: 'MonadCircleMono', category: 'coin' },
  { name: 'MonadMono', category: 'coin' },
  {
    name: 'Near',
    category: 'coin',
    ticker: 'NEAR',
    variants: ['', 'Mono'],
    brandColor: '#000000',
  },
  { name: 'NearMono', category: 'coin' },
  {
    name: 'Ondo',
    category: 'coin',
    ticker: 'ONDO',
    variants: ['', 'Mono'],
    brandColor: '#000000',
  },
  { name: 'OndoMono', category: 'coin' },
  {
    name: 'Op',
    category: 'coin',
    ticker: 'OP',
    variants: ['', 'Mono', 'Circle', 'CircleMono'],
    brandColor: '#ff0421',
  },
  { name: 'OpCircle', category: 'coin' },
  { name: 'OpCircleMono', category: 'coin' },
  { name: 'OpMono', category: 'coin' },
  {
    name: 'Pepe',
    category: 'coin',
    ticker: 'PEPE',
    variants: ['', 'Mono'],
    brandColor: '#4f9843',
  },
  { name: 'PepeMono', category: 'coin' },
  {
    name: 'Pol',
    category: 'coin',
    ticker: 'POL',
    variants: ['', 'Mono', 'Circle', 'CircleMono'],
    brandColor: '#670de5',
  },
  { name: 'PolCircle', category: 'coin' },
  { name: 'PolCircleMono', category: 'coin' },
  { name: 'PolMono', category: 'coin' },
  {
    name: 'Pyth',
    category: 'coin',
    ticker: 'PYTH',
    variants: ['', 'Mono'],
    brandColor: '#7142cf',
  },
  { name: 'PythMono', category: 'coin' },
  {
    name: 'Render',
    category: 'coin',
    ticker: 'RENDER',
    variants: ['', 'Mono'],
    brandColor: '#242532',
  },
  { name: 'RenderMono', category: 'coin' },
  {
    name: 'Ronin',
    category: 'coin',
    ticker: 'RON',
    variants: ['', 'Mono', 'Circle', 'CircleMono'],
    brandColor: '#004de5',
  },
  { name: 'RoninCircle', category: 'coin' },
  { name: 'RoninCircleMono', category: 'coin' },
  { name: 'RoninMono', category: 'coin' },
  {
    name: 'Sei',
    category: 'coin',
    ticker: 'SEI',
    variants: ['', 'Mono'],
    brandColor: '#600014',
  },
  { name: 'SeiMono', category: 'coin' },
  {
    name: 'Shib',
    category: 'coin',
    ticker: 'SHIB',
    variants: ['', 'Mono'],
    brandColor: '#e85f24',
  },
  { name: 'ShibMono', category: 'coin' },
  {
    name: 'Sky',
    category: 'coin',
    ticker: 'SKY',
    variants: ['', 'Mono', 'Circle', 'CircleMono'],
    brandColor: '#0075ff',
  },
  { name: 'SkyCircle', category: 'coin' },
  { name: 'SkyCircleMono', category: 'coin' },
  { name: 'SkyMono', category: 'coin' },
  {
    name: 'Sol',
    category: 'coin',
    ticker: 'SOL',
    variants: ['', 'Mono', 'Circle', 'CircleMono'],
    brandColor: '#9945ff',
  },
  { name: 'SolCircle', category: 'coin' },
  { name: 'SolCircleMono', category: 'coin' },
  { name: 'SolMono', category: 'coin' },
  {
    name: 'Sonic',
    category: 'coin',
    ticker: 'S',
    variants: ['', 'Mono', 'Circle', 'CircleMono'],
    brandColor: '#fac461',
  },
  { name: 'SonicCircle', category: 'coin' },
  { name: 'SonicCircleMono', category: 'coin' },
  { name: 'SonicMono', category: 'coin' },
  {
    name: 'Strk',
    category: 'coin',
    ticker: 'STRK',
    variants: ['', 'Mono', 'Circle', 'CircleMono', 'Square', 'SquareMono'],
    brandColor: '#ec796b',
  },
  { name: 'StrkCircle', category: 'coin' },
  { name: 'StrkCircleMono', category: 'coin' },
  { name: 'StrkMono', category: 'coin' },
  { name: 'StrkSquare', category: 'coin' },
  { name: 'StrkSquareMono', category: 'coin' },
  {
    name: 'Stx',
    category: 'coin',
    ticker: 'STX',
    variants: ['', 'Mono'],
    brandColor: '#fc6432',
  },
  { name: 'StxMono', category: 'coin' },
  {
    name: 'Sui',
    category: 'coin',
    ticker: 'SUI',
    variants: ['', 'Mono'],
    brandColor: '#298dff',
  },
  { name: 'SuiMono', category: 'coin' },
  {
    name: 'Taiko',
    category: 'coin',
    ticker: 'TAIKO',
    variants: ['', 'Mono', 'Circle', 'CircleMono'],
    brandColor: '#e81899',
  },
  { name: 'TaikoCircle', category: 'coin' },
  { name: 'TaikoCircleMono', category: 'coin' },
  { name: 'TaikoMono', category: 'coin' },
  {
    name: 'Tao',
    category: 'coin',
    ticker: 'TAO',
    variants: ['', 'Mono'],
    brandColor: '#000000',
  },
  { name: 'TaoMono', category: 'coin' },
  {
    name: 'Tia',
    category: 'coin',
    ticker: 'TIA',
    variants: ['', 'Mono'],
    brandColor: '#5640d1',
  },
  { name: 'TiaMono', category: 'coin' },
  {
    name: 'Ton',
    category: 'coin',
    ticker: 'TON',
    variants: ['', 'Mono'],
    brandColor: '#0098ea',
  },
  { name: 'TonMono', category: 'coin' },
  {
    name: 'Trx',
    category: 'coin',
    ticker: 'TRX',
    variants: ['', 'Mono'],
    brandColor: '#ea0029',
  },
  { name: 'TrxMono', category: 'coin' },
  {
    name: 'Uni',
    category: 'coin',
    ticker: 'UNI',
    variants: ['', 'Mono'],
    brandColor: '#f50db4',
  },
  { name: 'UniMono', category: 'coin' },
  {
    name: 'Usdc',
    category: 'coin',
    ticker: 'USDC',
    variants: ['', 'Mono', 'Circle', 'CircleMono'],
    brandColor: '#0b53bf',
  },
  { name: 'UsdcCircle', category: 'coin' },
  { name: 'UsdcCircleMono', category: 'coin' },
  { name: 'UsdcMono', category: 'coin' },
  {
    name: 'Usde',
    category: 'coin',
    ticker: 'USDE',
    variants: ['', 'Mono'],
    brandColor: '#111111',
  },
  { name: 'UsdeMono', category: 'coin' },
  {
    name: 'Usds',
    category: 'coin',
    ticker: 'USDS',
    variants: ['', 'Mono'],
    brandColor: '#ffd232',
  },
  { name: 'UsdsMono', category: 'coin' },
  {
    name: 'Usdt',
    category: 'coin',
    ticker: 'USDT',
    variants: ['', 'Mono', 'Circle', 'CircleMono'],
    brandColor: '#009393',
  },
  { name: 'UsdtCircle', category: 'coin' },
  { name: 'UsdtCircleMono', category: 'coin' },
  { name: 'UsdtMono', category: 'coin' },
  {
    name: 'Vet',
    category: 'coin',
    ticker: 'VET',
    variants: ['', 'Mono'],
    brandColor: '#7266ff',
  },
  { name: 'VetMono', category: 'coin' },
  {
    name: 'Wld',
    category: 'coin',
    ticker: 'WLD',
    variants: ['', 'Mono'],
    brandColor: '#000000',
  },
  { name: 'WldMono', category: 'coin' },
  {
    name: 'Xlm',
    category: 'coin',
    ticker: 'XLM',
    variants: ['', 'Mono'],
    brandColor: '#000000',
  },
  { name: 'XlmMono', category: 'coin' },
  {
    name: 'Xmr',
    category: 'coin',
    ticker: 'XMR',
    variants: ['', 'Mono'],
    brandColor: '#ff6600',
  },
  { name: 'XmrMono', category: 'coin' },
  {
    name: 'Xrp',
    category: 'coin',
    ticker: 'XRP',
    variants: ['', 'Mono', 'Circle', 'CircleMono'],
    brandColor: '#141414',
  },
  { name: 'XrpCircle', category: 'coin' },
  { name: 'XrpCircleMono', category: 'coin' },
  { name: 'XrpMono', category: 'coin' },
  {
    name: 'Zec',
    category: 'coin',
    ticker: 'ZEC',
    variants: ['', 'Mono'],
    brandColor: '#f4b728',
  },
  { name: 'ZecMono', category: 'coin' },
  {
    name: 'Aave',
    category: 'defi',
    slug: 'aave',
    variants: ['', 'Mono'],
    brandColor: '#9391f7',
  },
  { name: 'AaveMono', category: 'defi' },
  {
    name: 'Babylon',
    category: 'defi',
    slug: 'babylon',
    variants: ['', 'Mono'],
    brandColor: '#ce6533',
  },
  { name: 'BabylonMono', category: 'defi' },
  {
    name: 'Balancer',
    category: 'defi',
    slug: 'balancer',
    variants: ['', 'Mono'],
    brandColor: '#000000',
  },
  { name: 'BalancerMono', category: 'defi' },
  {
    name: 'Compound',
    category: 'defi',
    slug: 'compound',
    variants: ['', 'Mono'],
    aliases: ['comp'],
    brandColor: '#00d395',
  },
  { name: 'CompoundMono', category: 'defi' },
  {
    name: 'Convex',
    category: 'defi',
    slug: 'convex',
    variants: ['', 'Mono'],
    brandColor: '#1682fe',
  },
  { name: 'ConvexMono', category: 'defi' },
  {
    name: 'EigenLayer',
    category: 'defi',
    slug: 'eigenlayer',
    variants: ['', 'Mono'],
    aliases: ['eigen', 'eigencloud'],
    brandColor: '#1a0c6d',
  },
  { name: 'EigenLayerMono', category: 'defi' },
  {
    name: 'Ethena',
    category: 'defi',
    slug: 'ethena',
    variants: ['', 'Mono'],
    brandColor: '#040404',
  },
  { name: 'EthenaMono', category: 'defi' },
  {
    name: 'EtherFi',
    category: 'defi',
    slug: 'etherfi',
    variants: ['', 'Mono'],
    brandColor: '#29bcfa',
  },
  { name: 'EtherFiMono', category: 'defi' },
  {
    name: 'Frax',
    category: 'defi',
    slug: 'frax',
    variants: ['', 'Mono'],
    brandColor: '#000000',
  },
  { name: 'FraxMono', category: 'defi' },
  {
    name: 'Gmx',
    category: 'defi',
    slug: 'gmx',
    variants: ['', 'Mono'],
    brandColor: '#03d1cf',
  },
  { name: 'GmxMono', category: 'defi' },
  {
    name: 'Kamino',
    category: 'defi',
    slug: 'kamino',
    variants: ['', 'Mono'],
    brandColor: '#caf2fc',
  },
  { name: 'KaminoMono', category: 'defi' },
  {
    name: 'Lido',
    category: 'defi',
    slug: 'lido',
    variants: ['', 'Mono'],
    aliases: ['steth'],
    brandColor: '#0085ff',
  },
  { name: 'LidoMono', category: 'defi' },
  {
    name: 'Liquity',
    category: 'defi',
    slug: 'liquity',
    variants: ['', 'Mono'],
    brandColor: '#95cbf3',
  },
  { name: 'LiquityMono', category: 'defi' },
  {
    name: 'MakerDao',
    category: 'defi',
    deprecated: true,
    variants: ['', 'Mono'],
    brandColor: '#1bc4a3',
  },
  { name: 'MakerDaoMono', category: 'defi', deprecated: true },
  {
    name: 'Maple',
    category: 'defi',
    slug: 'maple',
    variants: ['', 'Mono'],
    brandColor: '#fc784a',
  },
  { name: 'MapleMono', category: 'defi' },
  {
    name: 'Morpho',
    category: 'defi',
    slug: 'morpho',
    variants: ['', 'Mono'],
    brandColor: '#2470ff',
  },
  { name: 'MorphoMono', category: 'defi' },
  {
    name: 'Pendle',
    category: 'defi',
    slug: 'pendle',
    variants: ['', 'Mono'],
    brandColor: '#1e4480',
  },
  { name: 'PendleMono', category: 'defi' },
  {
    name: 'RocketPool',
    category: 'defi',
    slug: 'rocketpool',
    variants: ['', 'Mono'],
    brandColor: '#f2681d',
  },
  { name: 'RocketPoolMono', category: 'defi' },
  {
    name: 'SafeProtocol',
    category: 'defi',
    slug: 'safeprotocol',
    variants: ['', 'Mono'],
    brandColor: '#1a1a1a',
  },
  { name: 'SafeProtocolMono', category: 'defi' },
  {
    name: 'Sky',
    category: 'defi',
    slug: 'sky',
    variants: ['', 'Mono', 'Circle', 'CircleMono'],
    brandColor: '#0075ff',
  },
  { name: 'SkyCircle', category: 'defi' },
  { name: 'SkyCircleMono', category: 'defi' },
  { name: 'SkyMono', category: 'defi' },
  {
    name: 'Spark',
    category: 'defi',
    slug: 'spark',
    variants: ['', 'Mono'],
    brandColor: '#fa43bd',
  },
  { name: 'SparkMono', category: 'defi' },
  {
    name: 'Synthetix',
    category: 'defi',
    slug: 'synthetix',
    variants: ['', 'Mono'],
    aliases: ['snx'],
    brandColor: '#00d1ff',
  },
  { name: 'SynthetixMono', category: 'defi' },
  {
    name: 'Venus',
    category: 'defi',
    slug: 'venus',
    variants: ['', 'Mono'],
    brandColor: '#5433ff',
  },
  { name: 'VenusMono', category: 'defi' },
  {
    name: 'Yearn',
    category: 'defi',
    slug: 'yearn',
    variants: ['', 'Mono'],
    brandColor: '#0657f9',
  },
  { name: 'YearnMono', category: 'defi' },
  {
    name: 'Aragon',
    category: 'devtool',
    variants: ['', 'Mono', 'Circle', 'CircleMono'],
    brandColor: '#3164fa',
  },
  { name: 'AragonCircle', category: 'devtool' },
  { name: 'AragonCircleMono', category: 'devtool' },
  { name: 'AragonMono', category: 'devtool' },
  {
    name: 'Cactus',
    category: 'devtool',
    variants: ['', 'Mono'],
    brandColor: '#0f1712',
  },
  { name: 'CactusMono', category: 'devtool' },
  {
    name: 'Chainlink',
    category: 'devtool',
    variants: ['', 'Mono'],
    brandColor: '#0847f7',
  },
  { name: 'ChainlinkMono', category: 'devtool' },
  {
    name: 'CollabLand',
    category: 'devtool',
    variants: ['', 'Mono'],
    brandColor: '#1a1a40',
  },
  { name: 'CollabLandMono', category: 'devtool' },
  {
    name: 'EthersJs',
    category: 'devtool',
    variants: ['', 'Mono'],
    brandColor: '#1d4c7c',
  },
  { name: 'EthersJsMono', category: 'devtool' },
  {
    name: 'Hardhat',
    category: 'devtool',
    variants: ['', 'Mono'],
    brandColor: '#fff100',
  },
  { name: 'HardhatMono', category: 'devtool' },
  {
    name: 'Moralis',
    category: 'devtool',
    variants: ['', 'Mono'],
    brandColor: '#3a7aff',
  },
  { name: 'MoralisMono', category: 'devtool' },
  {
    name: 'OpenZeppelin',
    category: 'devtool',
    variants: ['', 'Mono'],
    brandColor: '#2e99ff',
  },
  { name: 'OpenZeppelinMono', category: 'devtool' },
  {
    name: 'Privy',
    category: 'devtool',
    variants: ['', 'Mono'],
    brandColor: '#010110',
  },
  { name: 'PrivyMono', category: 'devtool' },
  {
    name: 'Remix',
    category: 'devtool',
    variants: ['', 'Mono'],
    brandColor: '#007aa6',
  },
  { name: 'RemixMono', category: 'devtool' },
  {
    name: 'Solidity',
    category: 'devtool',
    variants: ['', 'Mono'],
    brandColor: '#2b247c',
  },
  { name: 'SolidityMono', category: 'devtool' },
  {
    name: 'Tally',
    category: 'devtool',
    deprecated: true,
    variants: ['', 'Mono'],
    brandColor: '#2a21a3',
  },
  { name: 'TallyMono', category: 'devtool', deprecated: true },
  {
    name: 'Tenderly',
    category: 'devtool',
    variants: ['', 'Mono'],
    brandColor: '#9573f5',
  },
  { name: 'TenderlyMono', category: 'devtool' },
  {
    name: 'TheGraph',
    category: 'devtool',
    variants: ['', 'Mono'],
    aliases: ['grt'],
    brandColor: '#6f4cff',
  },
  { name: 'TheGraphMono', category: 'devtool' },
  {
    name: 'Thirdweb',
    category: 'devtool',
    variants: ['', 'Mono'],
    brandColor: '#ff00a8',
  },
  { name: 'ThirdwebMono', category: 'devtool' },
  {
    name: 'Viem',
    category: 'devtool',
    variants: ['', 'Mono'],
    brandColor: '#1e1e20',
  },
  { name: 'ViemMono', category: 'devtool' },
  {
    name: 'Wagmi',
    category: 'devtool',
    variants: ['', 'Mono'],
    brandColor: '#1b1b1b',
  },
  { name: 'WagmiMono', category: 'devtool' },
  {
    name: 'Web3Js',
    category: 'devtool',
    deprecated: true,
    variants: ['', 'Mono'],
    brandColor: '#f16822',
  },
  { name: 'Web3JsMono', category: 'devtool', deprecated: true },
  {
    name: 'Aerodrome',
    category: 'dex',
    slug: 'aerodrome',
    variants: ['', 'Mono'],
    brandColor: '#0433ff',
  },
  { name: 'AerodromeMono', category: 'dex' },
  {
    name: 'Camelot',
    category: 'dex',
    slug: 'camelot',
    variants: ['', 'Mono'],
    brandColor: '#fff3d4',
  },
  { name: 'CamelotMono', category: 'dex' },
  {
    name: 'CowProtocol',
    category: 'dex',
    slug: 'cowprotocol',
    variants: ['', 'Mono'],
    brandColor: '#490072',
  },
  { name: 'CowProtocolMono', category: 'dex' },
  {
    name: 'Dydx',
    category: 'dex',
    slug: 'dydx',
    variants: ['', 'Mono', 'Inverted', 'Square', 'SquareMono'],
    brandColor: '#6966ff',
  },
  { name: 'DydxInverted', category: 'dex' },
  { name: 'DydxMono', category: 'dex' },
  { name: 'DydxSquare', category: 'dex' },
  { name: 'DydxSquareMono', category: 'dex' },
  {
    name: 'Ekubo',
    category: 'dex',
    slug: 'ekubo',
    variants: ['', 'Mono'],
    brandColor: '#101010',
  },
  { name: 'EkuboMono', category: 'dex' },
  {
    name: 'Fluid',
    category: 'dex',
    slug: 'fluid',
    variants: ['', 'Mono'],
    brandColor: '#000000',
  },
  { name: 'FluidMono', category: 'dex' },
  {
    name: 'Hyperliquid',
    category: 'dex',
    slug: 'hyperliquid',
    variants: ['', 'Mono'],
    brandColor: '#97fce4',
  },
  { name: 'HyperliquidMono', category: 'dex' },
  {
    name: 'Jupiter',
    category: 'dex',
    slug: 'jupiter',
    variants: ['', 'Mono', 'Circle', 'CircleMono'],
    brandColor: '#c7f284',
  },
  { name: 'JupiterCircle', category: 'dex' },
  { name: 'JupiterCircleMono', category: 'dex' },
  { name: 'JupiterMono', category: 'dex' },
  {
    name: 'Meteora',
    category: 'dex',
    slug: 'meteora',
    variants: ['', 'Mono'],
    brandColor: '#f5bd00',
  },
  { name: 'MeteoraMono', category: 'dex' },
  {
    name: 'Odos',
    category: 'dex',
    deprecated: true,
    variants: ['', 'Mono'],
    brandColor: '#ff5100',
  },
  { name: 'OdosMono', category: 'dex', deprecated: true },
  {
    name: 'Oneinch',
    category: 'dex',
    slug: 'oneinch',
    variants: ['', 'Mono'],
    aliases: ['1inch'],
    brandColor: '#000000',
  },
  { name: 'OneinchMono', category: 'dex' },
  {
    name: 'Orca',
    category: 'dex',
    slug: 'orca',
    variants: ['', 'Mono'],
    brandColor: '#ffd15c',
  },
  { name: 'OrcaMono', category: 'dex' },
  {
    name: 'Osmosis',
    category: 'dex',
    slug: 'osmosis',
    variants: ['', 'Mono'],
    brandColor: '#000292',
  },
  { name: 'OsmosisMono', category: 'dex' },
  {
    name: 'PancakeSwap',
    category: 'dex',
    slug: 'pancakeswap',
    variants: ['', 'Mono'],
    aliases: ['cake'],
    brandColor: '#633001',
  },
  { name: 'PancakeSwapMono', category: 'dex' },
  {
    name: 'ParaSwap',
    category: 'dex',
    deprecated: true,
    variants: ['', 'Mono'],
    brandColor: '#2669f5',
  },
  { name: 'ParaSwapMono', category: 'dex', deprecated: true },
  {
    name: 'Raydium',
    category: 'dex',
    slug: 'raydium',
    variants: ['', 'Mono'],
    aliases: ['ray'],
    brandColor: '#c200fb',
  },
  { name: 'RaydiumMono', category: 'dex' },
  {
    name: 'SushiSwap',
    category: 'dex',
    slug: 'sushiswap',
    variants: ['', 'Mono'],
    aliases: ['sushi'],
    brandColor: '#27b0e6',
  },
  { name: 'SushiSwapMono', category: 'dex' },
  {
    name: 'Uniswap',
    category: 'dex',
    slug: 'uniswap',
    variants: ['', 'Mono'],
    brandColor: '#f50db4',
  },
  { name: 'UniswapMono', category: 'dex' },
  {
    name: 'Velodrome',
    category: 'dex',
    slug: 'velodrome',
    variants: ['', 'Mono'],
    brandColor: '#ff1100',
  },
  { name: 'VelodromeMono', category: 'dex' },
  {
    name: 'Velora',
    category: 'dex',
    slug: 'velora',
    variants: ['', 'Mono'],
    brandColor: '#ff9e00',
  },
  { name: 'VeloraMono', category: 'dex' },
  {
    name: 'Ens',
    category: 'domain',
    variants: ['', 'Mono', 'Circle', 'CircleMono'],
    brandColor: '#0080bc',
  },
  { name: 'EnsCircle', category: 'domain' },
  { name: 'EnsCircleMono', category: 'domain' },
  { name: 'EnsMono', category: 'domain' },
  {
    name: 'UnstoppableDomains',
    category: 'domain',
    variants: ['', 'Mono'],
    brandColor: '#00c9ff',
  },
  { name: 'UnstoppableDomainsMono', category: 'domain' },
  {
    name: 'Binance',
    category: 'exchange',
    slug: 'binance',
    variants: ['', 'Mono'],
    aliases: ['bnb'],
    brandColor: '#f0b90b',
  },
  { name: 'BinanceMono', category: 'exchange' },
  {
    name: 'Bitfinex',
    category: 'exchange',
    slug: 'bitfinex',
    variants: ['', 'Mono'],
    brandColor: '#03ca9b',
  },
  { name: 'BitfinexMono', category: 'exchange' },
  {
    name: 'Bitget',
    category: 'exchange',
    slug: 'bitget',
    variants: ['', 'Mono'],
    brandColor: '#00f0ff',
  },
  { name: 'BitgetMono', category: 'exchange' },
  {
    name: 'Bithumb',
    category: 'exchange',
    slug: 'bithumb',
    variants: ['', 'Mono'],
    brandColor: '#ff6c00',
  },
  { name: 'BithumbMono', category: 'exchange' },
  {
    name: 'Bitstamp',
    category: 'exchange',
    slug: 'bitstamp',
    variants: ['', 'Mono', 'Circle', 'CircleMono'],
    brandColor: '#003b2f',
  },
  { name: 'BitstampCircle', category: 'exchange' },
  { name: 'BitstampCircleMono', category: 'exchange' },
  { name: 'BitstampMono', category: 'exchange' },
  {
    name: 'Bybit',
    category: 'exchange',
    slug: 'bybit',
    variants: ['', 'Mono', 'Inverted'],
    brandColor: '#f7a600',
  },
  { name: 'BybitInverted', category: 'exchange' },
  { name: 'BybitMono', category: 'exchange' },
  {
    name: 'Coinbase',
    category: 'exchange',
    slug: 'coinbase',
    variants: ['', 'Mono', 'Circle', 'CircleMono', 'CircleAlt'],
    brandColor: '#0052ff',
  },
  { name: 'CoinbaseCircle', category: 'exchange' },
  { name: 'CoinbaseCircleAlt', category: 'exchange' },
  { name: 'CoinbaseCircleMono', category: 'exchange' },
  { name: 'CoinbaseMono', category: 'exchange' },
  {
    name: 'CryptoCom',
    category: 'exchange',
    slug: 'cryptocom',
    variants: ['', 'Mono'],
    brandColor: '#3c62d1',
  },
  { name: 'CryptoComMono', category: 'exchange' },
  {
    name: 'Deribit',
    category: 'exchange',
    slug: 'deribit',
    variants: ['', 'Mono'],
    brandColor: '#0052ff',
  },
  { name: 'DeribitMono', category: 'exchange' },
  {
    name: 'Gate',
    category: 'exchange',
    slug: 'gate',
    variants: ['', 'Mono'],
    brandColor: '#2354e6',
  },
  { name: 'GateMono', category: 'exchange' },
  { name: 'Gateio', category: 'exchange', deprecated: true },
  { name: 'GateioMono', category: 'exchange', deprecated: true },
  {
    name: 'Gemini',
    category: 'exchange',
    slug: 'gemini',
    variants: ['', 'Mono', 'Square', 'SquareMono'],
    brandColor: '#ff4809',
  },
  { name: 'GeminiMono', category: 'exchange' },
  { name: 'GeminiSquare', category: 'exchange' },
  { name: 'GeminiSquareMono', category: 'exchange' },
  {
    name: 'Htx',
    category: 'exchange',
    slug: 'htx',
    variants: ['', 'Mono', 'Inverted'],
    brandColor: '#00003e',
  },
  { name: 'HtxInverted', category: 'exchange' },
  { name: 'HtxMono', category: 'exchange' },
  {
    name: 'Kraken',
    category: 'exchange',
    slug: 'kraken',
    variants: ['', 'Mono'],
    brandColor: '#7132f5',
  },
  { name: 'KrakenMono', category: 'exchange' },
  {
    name: 'KuCoin',
    category: 'exchange',
    slug: 'kucoin',
    variants: ['', 'Mono'],
    brandColor: '#00b47d',
  },
  { name: 'KuCoinMono', category: 'exchange' },
  {
    name: 'Mexc',
    category: 'exchange',
    slug: 'mexc',
    variants: ['', 'Mono'],
    brandColor: '#0057ff',
  },
  { name: 'MexcMono', category: 'exchange' },
  {
    name: 'Okx',
    category: 'exchange',
    slug: 'okx',
    variants: ['', 'Mono'],
    aliases: ['okb'],
    brandColor: '#000000',
  },
  { name: 'OkxMono', category: 'exchange' },
  {
    name: 'Phemex',
    category: 'exchange',
    slug: 'phemex',
    variants: ['', 'Mono'],
    brandColor: '#87ec26',
  },
  { name: 'PhemexMono', category: 'exchange' },
  {
    name: 'Upbit',
    category: 'exchange',
    slug: 'upbit',
    variants: ['', 'Mono'],
    brandColor: '#093687',
  },
  { name: 'UpbitMono', category: 'exchange' },
  {
    name: 'Arbiscan',
    category: 'explorer',
    variants: ['', 'Mono'],
    brandColor: '#213147',
  },
  { name: 'ArbiscanMono', category: 'explorer' },
  {
    name: 'Avascan',
    category: 'explorer',
    variants: ['', 'Mono', 'Wordmark', 'WordmarkMono'],
    brandColor: '#6d6df2',
  },
  { name: 'AvascanMono', category: 'explorer' },
  { name: 'AvascanWordmark', category: 'explorer' },
  { name: 'AvascanWordmarkMono', category: 'explorer' },
  {
    name: 'Basescan',
    category: 'explorer',
    variants: ['', 'Mono', 'Inverted'],
    brandColor: '#0052ff',
  },
  { name: 'BasescanInverted', category: 'explorer' },
  { name: 'BasescanMono', category: 'explorer' },
  {
    name: 'Blastscan',
    category: 'explorer',
    variants: ['', 'Mono', 'Light'],
    brandColor: '#fcfc03',
  },
  { name: 'BlastscanLight', category: 'explorer' },
  { name: 'BlastscanMono', category: 'explorer' },
  {
    name: 'Blockscout',
    category: 'explorer',
    variants: ['', 'Mono'],
    brandColor: '#5353d3',
  },
  { name: 'BlockscoutMono', category: 'explorer' },
  {
    name: 'Bscscan',
    category: 'explorer',
    variants: ['', 'Mono', 'Inverted'],
    brandColor: '#f0b90b',
  },
  { name: 'BscscanInverted', category: 'explorer' },
  { name: 'BscscanMono', category: 'explorer' },
  {
    name: 'Celoscan',
    category: 'explorer',
    variants: ['', 'Mono', 'Square', 'SquareMono'],
    brandColor: '#fcff52',
  },
  { name: 'CeloscanMono', category: 'explorer' },
  { name: 'CeloscanSquare', category: 'explorer' },
  { name: 'CeloscanSquareMono', category: 'explorer' },
  {
    name: 'Etherscan',
    category: 'explorer',
    variants: ['', 'Mono', 'Inverted'],
    brandColor: '#21325b',
  },
  { name: 'EtherscanInverted', category: 'explorer' },
  { name: 'EtherscanMono', category: 'explorer' },
  {
    name: 'Routescan',
    category: 'explorer',
    variants: ['', 'Mono'],
    brandColor: '#00ff7f',
  },
  { name: 'RoutescanMono', category: 'explorer' },
  {
    name: 'Solscan',
    category: 'explorer',
    variants: ['', 'Mono'],
    brandColor: '#c74ae3',
  },
  { name: 'SolscanMono', category: 'explorer' },
  {
    name: 'LooksRare',
    category: 'marketplace',
    variants: ['', 'Mono', 'Flat'],
    brandColor: '#0ce466',
  },
  { name: 'LooksRareFlat', category: 'marketplace' },
  { name: 'LooksRareMono', category: 'marketplace' },
  {
    name: 'MagicEden',
    category: 'marketplace',
    variants: ['', 'Mono', 'Wordmark', 'WordmarkMono'],
    brandColor: '#ec136d',
  },
  { name: 'MagicEdenFlat', category: 'marketplace', deprecated: true },
  { name: 'MagicEdenMono', category: 'marketplace' },
  { name: 'MagicEdenWordmark', category: 'marketplace' },
  { name: 'MagicEdenWordmarkFlat', category: 'marketplace', deprecated: true },
  { name: 'MagicEdenWordmarkMono', category: 'marketplace' },
  {
    name: 'OpenSea',
    category: 'marketplace',
    variants: ['', 'Mono', 'Symbol', 'SymbolMono'],
    brandColor: '#0086ff',
  },
  { name: 'OpenSeaAlt', category: 'marketplace', deprecated: true },
  { name: 'OpenSeaMono', category: 'marketplace' },
  { name: 'OpenSeaSymbol', category: 'marketplace' },
  { name: 'OpenSeaSymbolMono', category: 'marketplace' },
  {
    name: 'Tensor',
    category: 'marketplace',
    variants: ['', 'Mono'],
    brandColor: '#000000',
  },
  { name: 'TensorMono', category: 'marketplace' },
  {
    name: 'X2Y2',
    category: 'marketplace',
    deprecated: true,
    variants: ['', 'Mono'],
    brandColor: '#00e0ff',
  },
  { name: 'X2Y2Mono', category: 'marketplace', deprecated: true },
  {
    name: 'Alchemy',
    category: 'node',
    variants: ['', 'Mono'],
    brandColor: '#05d5ff',
  },
  { name: 'AlchemyMono', category: 'node' },
  {
    name: 'Ankr',
    category: 'node',
    variants: ['', 'Mono'],
    brandColor: '#356df3',
  },
  { name: 'AnkrMono', category: 'node' },
  {
    name: 'Chainstack',
    category: 'node',
    variants: ['', 'Mono'],
    brandColor: '#007bff',
  },
  { name: 'ChainstackMono', category: 'node' },
  {
    name: 'Drpc',
    category: 'node',
    variants: ['', 'Mono'],
    brandColor: '#49ff87',
  },
  { name: 'DrpcMono', category: 'node' },
  {
    name: 'Helius',
    category: 'node',
    variants: ['', 'Mono'],
    brandColor: '#e84125',
  },
  { name: 'HeliusMono', category: 'node' },
  {
    name: 'Infura',
    category: 'node',
    variants: ['', 'Mono'],
    brandColor: '#ff6b4a',
  },
  { name: 'InfuraMono', category: 'node' },
  {
    name: 'QuickNode',
    category: 'node',
    variants: ['', 'Mono'],
    brandColor: '#6cff75',
  },
  { name: 'QuickNodeMono', category: 'node' },
  {
    name: 'Api3',
    category: 'oracle',
    slug: 'api3',
    variants: ['', 'Mono'],
    brandColor: '#1f267b',
  },
  { name: 'Api3Mono', category: 'oracle' },
  {
    name: 'Band',
    category: 'oracle',
    slug: 'band',
    variants: ['', 'Mono'],
    brandColor: '#8f8fff',
  },
  { name: 'BandMono', category: 'oracle' },
  {
    name: 'Pyth',
    category: 'oracle',
    slug: 'pyth',
    variants: ['', 'Mono'],
    brandColor: '#7142cf',
  },
  { name: 'PythMono', category: 'oracle' },
  {
    name: 'RedStone',
    category: 'oracle',
    slug: 'redstone',
    variants: ['', 'Mono'],
    brandColor: '#ae0822',
  },
  { name: 'RedStoneMono', category: 'oracle' },
  {
    name: 'CoinLedger',
    category: 'portfolio',
    variants: ['', 'Mono'],
    brandColor: '#00c2ff',
  },
  { name: 'CoinLedgerMono', category: 'portfolio' },
  {
    name: 'Coinpanda',
    category: 'portfolio',
    variants: ['', 'Mono', 'Circle', 'CircleMono', 'Square', 'SquareMono'],
    brandColor: '#246aff',
  },
  { name: 'CoinpandaCircle', category: 'portfolio' },
  { name: 'CoinpandaCircleMono', category: 'portfolio' },
  { name: 'CoinpandaMono', category: 'portfolio' },
  { name: 'CoinpandaSquare', category: 'portfolio' },
  { name: 'CoinpandaSquareMono', category: 'portfolio' },
  {
    name: 'DeBank',
    category: 'portfolio',
    variants: ['', 'Mono'],
    brandColor: '#fe815f',
  },
  { name: 'DeBankMono', category: 'portfolio' },
  {
    name: 'Zapper',
    category: 'portfolio',
    variants: ['', 'Mono'],
    brandColor: '#784ffe',
  },
  { name: 'ZapperMono', category: 'portfolio' },
  {
    name: 'Arweave',
    category: 'storage',
    variants: ['', 'Mono'],
    aliases: ['arw'],
    brandColor: '#222326',
  },
  { name: 'ArweaveMono', category: 'storage' },
  {
    name: 'Ipfs',
    category: 'storage',
    variants: ['', 'Mono'],
    brandColor: '#469ea2',
  },
  { name: 'IpfsMono', category: 'storage' },
  {
    name: 'NftStorage',
    category: 'storage',
    deprecated: true,
    variants: ['', 'Mono'],
    brandColor: '#f5c32c',
  },
  { name: 'NftStorageMono', category: 'storage', deprecated: true },
  {
    name: 'Pinata',
    category: 'storage',
    variants: ['', 'Mono'],
    brandColor: '#ce3f8f',
  },
  { name: 'PinataMono', category: 'storage' },
  {
    name: 'Walrus',
    category: 'storage',
    variants: ['', 'Mono'],
    brandColor: '#000000',
  },
  { name: 'WalrusMono', category: 'storage' },
  {
    name: 'Arkham',
    category: 'tracker',
    variants: ['', 'Mono'],
    aliases: ['arkham-intelligence', 'arkm'],
    brandColor: '#000000',
  },
  { name: 'ArkhamMono', category: 'tracker' },
  {
    name: 'CoinGecko',
    category: 'tracker',
    variants: ['', 'Mono'],
    brandColor: '#4bcc00',
  },
  { name: 'CoinGeckoMono', category: 'tracker' },
  {
    name: 'CoinMarketCap',
    category: 'tracker',
    variants: ['', 'Mono', 'Circle', 'CircleMono'],
    brandColor: '#3861fb',
  },
  { name: 'CoinMarketCapCircle', category: 'tracker' },
  { name: 'CoinMarketCapCircleMono', category: 'tracker' },
  { name: 'CoinMarketCapMono', category: 'tracker' },
  {
    name: 'DefiLlama',
    category: 'tracker',
    variants: ['', 'Mono'],
    brandColor: '#b3d2ff',
  },
  { name: 'DefiLlamaMono', category: 'tracker' },
  {
    name: 'DexScreener',
    category: 'tracker',
    variants: ['', 'Mono', 'SymbolMono'],
    brandColor: '#09090b',
  },
  { name: 'DexScreenerMono', category: 'tracker' },
  { name: 'DexScreenerSymbolMono', category: 'tracker' },
  {
    name: 'Dune',
    category: 'tracker',
    variants: ['', 'Mono', 'Square', 'SquareMono'],
    brandColor: '#f4603e',
  },
  { name: 'DuneMono', category: 'tracker' },
  { name: 'DuneSquare', category: 'tracker' },
  { name: 'DuneSquareMono', category: 'tracker' },
  {
    name: 'Nansen',
    category: 'tracker',
    variants: ['', 'Mono'],
    brandColor: '#00ffa7',
  },
  { name: 'NansenMono', category: 'tracker' },
  { name: 'Argent', category: 'wallet', deprecated: true },
  { name: 'ArgentMono', category: 'wallet', deprecated: true },
  {
    name: 'Backpack',
    category: 'wallet',
    slug: 'backpack',
    variants: ['', 'Mono'],
    brandColor: '#e33e3f',
  },
  { name: 'BackpackMono', category: 'wallet' },
  { name: 'BackpackWallet', category: 'wallet', deprecated: true },
  { name: 'BackpackWalletMono', category: 'wallet', deprecated: true },
  {
    name: 'BitgetWallet',
    category: 'wallet',
    slug: 'bitgetwallet',
    variants: ['', 'Mono'],
    brandColor: '#00f0ff',
  },
  { name: 'BitgetWalletMono', category: 'wallet' },
  {
    name: 'Brave',
    category: 'wallet',
    slug: 'brave',
    variants: ['', 'Mono'],
    brandColor: '#ff2000',
  },
  { name: 'BraveMono', category: 'wallet' },
  {
    name: 'CoinbaseWallet',
    category: 'wallet',
    slug: 'coinbasewallet',
    variants: ['', 'Mono', 'Circle', 'CircleMono', 'Square', 'SquareMono'],
    brandColor: '#0000ff',
  },
  { name: 'CoinbaseWalletCircle', category: 'wallet' },
  { name: 'CoinbaseWalletCircleMono', category: 'wallet' },
  { name: 'CoinbaseWalletMono', category: 'wallet' },
  { name: 'CoinbaseWalletSquare', category: 'wallet' },
  { name: 'CoinbaseWalletSquareMono', category: 'wallet' },
  {
    name: 'Daedalus',
    category: 'wallet',
    slug: 'daedalus',
    variants: ['', 'Mono'],
    brandColor: '#82ff65',
  },
  { name: 'DaedalusMono', category: 'wallet' },
  { name: 'DaedalusWallet', category: 'wallet', deprecated: true },
  { name: 'DaedalusWalletMono', category: 'wallet', deprecated: true },
  {
    name: 'Enkrypt',
    category: 'wallet',
    slug: 'enkrypt',
    variants: ['', 'Mono'],
    brandColor: '#c549ff',
  },
  { name: 'EnkryptMono', category: 'wallet' },
  {
    name: 'Exodus',
    category: 'wallet',
    slug: 'exodus',
    variants: ['', 'Mono'],
    brandColor: '#0b46f9',
  },
  { name: 'ExodusMono', category: 'wallet' },
  {
    name: 'ImToken',
    category: 'wallet',
    slug: 'imtoken',
    variants: ['', 'Mono'],
    brandColor: '#0cc5ff',
  },
  { name: 'ImTokenMono', category: 'wallet' },
  {
    name: 'Keplr',
    category: 'wallet',
    slug: 'keplr',
    variants: ['', 'Mono'],
    brandColor: '#14afeb',
  },
  { name: 'KeplrMono', category: 'wallet' },
  {
    name: 'Lace',
    category: 'wallet',
    slug: 'lace',
    variants: ['', 'Mono'],
    brandColor: '#fd9a7a',
  },
  { name: 'LaceMono', category: 'wallet' },
  {
    name: 'Ledger',
    category: 'wallet',
    slug: 'ledger',
    variants: ['', 'Mono'],
    brandColor: '#000000',
  },
  { name: 'LedgerMono', category: 'wallet' },
  {
    name: 'MetaMask',
    category: 'wallet',
    slug: 'metamask',
    variants: ['', 'Mono', 'Circle', 'CircleMono', 'Square', 'SquareMono'],
    aliases: ['metamask'],
    brandColor: '#ff5c16',
  },
  { name: 'MetaMaskAlt', category: 'wallet', deprecated: true },
  { name: 'MetaMaskCircle', category: 'wallet' },
  { name: 'MetaMaskCircleMono', category: 'wallet' },
  { name: 'MetaMaskMono', category: 'wallet' },
  { name: 'MetaMaskSquare', category: 'wallet' },
  { name: 'MetaMaskSquareMono', category: 'wallet' },
  {
    name: 'NamiWallet',
    category: 'wallet',
    deprecated: true,
    variants: ['', 'Mono'],
    brandColor: '#349ea3',
  },
  { name: 'NamiWalletMono', category: 'wallet', deprecated: true },
  { name: 'OKXWallet', category: 'wallet', deprecated: true },
  { name: 'OKXWalletMono', category: 'wallet', deprecated: true },
  {
    name: 'OkxWallet',
    category: 'wallet',
    slug: 'okxwallet',
    variants: ['', 'Mono'],
    brandColor: '#000000',
  },
  { name: 'OkxWalletMono', category: 'wallet' },
  {
    name: 'Petra',
    category: 'wallet',
    slug: 'petra',
    variants: ['', 'Mono'],
    brandColor: '#5a3fff',
  },
  { name: 'PetraMono', category: 'wallet' },
  {
    name: 'Phantom',
    category: 'wallet',
    slug: 'phantom',
    variants: ['', 'Mono', 'Circle', 'CircleMono', 'Square', 'SquareMono'],
    brandColor: '#ab9ff2',
  },
  { name: 'PhantomCircle', category: 'wallet' },
  { name: 'PhantomCircleMono', category: 'wallet' },
  { name: 'PhantomMono', category: 'wallet' },
  { name: 'PhantomSquare', category: 'wallet' },
  { name: 'PhantomSquareMono', category: 'wallet' },
  { name: 'PhantomSymbolMono', category: 'wallet', deprecated: true },
  { name: 'PhantomWallet', category: 'wallet', deprecated: true },
  { name: 'PhantomWalletCircle', category: 'wallet', deprecated: true },
  { name: 'PhantomWalletCircleMono', category: 'wallet', deprecated: true },
  { name: 'PhantomWalletMono', category: 'wallet', deprecated: true },
  { name: 'PhantomWalletSquare', category: 'wallet', deprecated: true },
  { name: 'PhantomWalletSquareMono', category: 'wallet', deprecated: true },
  { name: 'PhantomWalletSymbolMono', category: 'wallet', deprecated: true },
  {
    name: 'PolkadotJs',
    category: 'wallet',
    slug: 'polkadotjs',
    variants: ['', 'Mono'],
    brandColor: '#ff8c00',
  },
  { name: 'PolkadotJsMono', category: 'wallet' },
  {
    name: 'Rabby',
    category: 'wallet',
    slug: 'rabby',
    variants: ['', 'Mono'],
    brandColor: '#8697ff',
  },
  { name: 'RabbyMono', category: 'wallet' },
  {
    name: 'Rainbow',
    category: 'wallet',
    slug: 'rainbow',
    variants: [
      '',
      'Mono',
      'Symbol',
      'SymbolMono',
      'Circle',
      'CircleMono',
      'Square',
      'SquareMono',
    ],
    brandColor: '#ff4000',
  },
  { name: 'RainbowCircle', category: 'wallet' },
  { name: 'RainbowCircleMono', category: 'wallet' },
  { name: 'RainbowMono', category: 'wallet' },
  { name: 'RainbowSquare', category: 'wallet' },
  { name: 'RainbowSquareMono', category: 'wallet' },
  { name: 'RainbowSymbol', category: 'wallet' },
  { name: 'RainbowSymbolMono', category: 'wallet' },
  { name: 'RainbowWallet', category: 'wallet', deprecated: true },
  { name: 'RainbowWalletCircle', category: 'wallet', deprecated: true },
  { name: 'RainbowWalletCircleMono', category: 'wallet', deprecated: true },
  { name: 'RainbowWalletMono', category: 'wallet', deprecated: true },
  { name: 'RainbowWalletSquare', category: 'wallet', deprecated: true },
  { name: 'RainbowWalletSquareMono', category: 'wallet', deprecated: true },
  { name: 'RainbowWalletSymbol', category: 'wallet', deprecated: true },
  { name: 'RainbowWalletSymbolMono', category: 'wallet', deprecated: true },
  {
    name: 'Ready',
    category: 'wallet',
    slug: 'ready',
    variants: ['', 'Mono'],
    brandColor: '#ff875b',
  },
  { name: 'ReadyMono', category: 'wallet' },
  {
    name: 'Safe',
    category: 'wallet',
    slug: 'safe',
    variants: ['', 'Mono'],
    aliases: ['gnosis'],
    brandColor: '#1a1a1a',
  },
  { name: 'SafeMono', category: 'wallet' },
  {
    name: 'Solflare',
    category: 'wallet',
    slug: 'solflare',
    variants: ['', 'Mono'],
    brandColor: '#ffef46',
  },
  { name: 'SolflareMono', category: 'wallet' },
  {
    name: 'SubWallet',
    category: 'wallet',
    slug: 'subwallet',
    variants: ['', 'Mono'],
    brandColor: '#61fec0',
  },
  { name: 'SubWalletMono', category: 'wallet' },
  {
    name: 'Tangem',
    category: 'wallet',
    slug: 'tangem',
    variants: ['', 'Mono'],
    brandColor: '#1e1e1e',
  },
  { name: 'TangemMono', category: 'wallet' },
  {
    name: 'Trezor',
    category: 'wallet',
    slug: 'trezor',
    variants: ['', 'Mono'],
    brandColor: '#000000',
  },
  { name: 'TrezorMono', category: 'wallet' },
  {
    name: 'TrustWallet',
    category: 'wallet',
    slug: 'trustwallet',
    variants: ['', 'Mono', 'Square', 'SquareMono', 'Circle', 'CircleMono'],
    brandColor: '#0500ff',
  },
  { name: 'TrustWalletCircle', category: 'wallet' },
  { name: 'TrustWalletCircleMono', category: 'wallet' },
  { name: 'TrustWalletMono', category: 'wallet' },
  { name: 'TrustWalletSquare', category: 'wallet' },
  { name: 'TrustWalletSquareMono', category: 'wallet' },
  {
    name: 'UniswapWallet',
    category: 'wallet',
    slug: 'uniswapwallet',
    variants: ['', 'Mono'],
    brandColor: '#f50db4',
  },
  { name: 'UniswapWalletMono', category: 'wallet' },
  {
    name: 'WalletConnect',
    category: 'wallet',
    slug: 'walletconnect',
    variants: ['', 'Mono', 'Circle', 'CircleMono', 'Square', 'SquareMono'],
    aliases: ['wc'],
    brandColor: '#0988f0',
  },
  { name: 'WalletConnectCircle', category: 'wallet' },
  { name: 'WalletConnectCircleMono', category: 'wallet' },
  { name: 'WalletConnectMono', category: 'wallet' },
  { name: 'WalletConnectSquare', category: 'wallet' },
  { name: 'WalletConnectSquareMono', category: 'wallet' },
  {
    name: 'Xverse',
    category: 'wallet',
    slug: 'xverse',
    variants: ['', 'Mono'],
    brandColor: '#ee7a30',
  },
  { name: 'XverseMono', category: 'wallet' },
  {
    name: 'Yoroi',
    category: 'wallet',
    slug: 'yoroi',
    variants: ['', 'Mono'],
    brandColor: '#4b63f6',
  },
  { name: 'YoroiMono', category: 'wallet' },
  { name: 'YoroiWallet', category: 'wallet', deprecated: true },
  { name: 'YoroiWalletMono', category: 'wallet', deprecated: true },
  {
    name: 'Zerion',
    category: 'wallet',
    slug: 'zerion',
    variants: ['', 'Mono', 'Circle', 'CircleMono', 'Square', 'SquareMono'],
    brandColor: '#2461ed',
  },
  { name: 'ZerionCircle', category: 'wallet' },
  { name: 'ZerionCircleMono', category: 'wallet' },
  { name: 'ZerionMono', category: 'wallet' },
  { name: 'ZerionSquare', category: 'wallet' },
  { name: 'ZerionSquareMono', category: 'wallet' },
];
