// Auto-generated by scripts/build-icons/cli.ts from icons/<category>/<slug>.json
// — do not edit manually. Regenerate: pnpm run generate-icons

import type { IconName } from './utils';

/**
 * Names of all deprecated icon exports in this package.
 *
 * Use this to filter deprecated aliases from icon lists without maintaining
 * a separate copy in your app. `has()` accepts any string, so keys of a
 * module namespace can be tested directly.
 *
 * @example
 * ```ts
 * import * as icons from 'react-web3-icons';
 * import { DEPRECATED_ICON_NAMES } from 'react-web3-icons';
 *
 * // Get current (non-deprecated) icon names, excluding non-icon exports
 * const activeIconNames = Object.keys(icons).filter(
 *   name =>
 *     !DEPRECATED_ICON_NAMES.has(name) &&
 *     name !== 'DEPRECATED_ICON_NAMES',
 * );
 * ```
 */
export const DEPRECATED_ICON_NAMES: ReadonlySet<IconName> & {
  has(name: string): boolean;
} = new Set<IconName>([
  // icons/bridge/hop-protocol.json
  'HopProtocol',
  'HopProtocolMono',
  // icons/chain/binance-smart-chain.json
  'BinanceSmartChain',
  'BinanceSmartChainMono',
  'BinanceSmartChainCircle',
  'BinanceSmartChainSquare',
  'BinanceSmartChainSquareMono',
  'BinanceSmartChainCircleMono',
  // icons/chain/fantom.json
  'Fantom',
  'FantomMono',
  // icons/chain/immutable-x.json
  'ImmutableX',
  'ImmutableXMono',
  // icons/chain/starknet.json
  'StarkNet',
  'StarkNetMono',
  'StarkNetCircle',
  'StarkNetSquare',
  'StarkNetSquareMono',
  'StarkNetCircleMono',
  // icons/chain/zksync.json
  'ZkSync',
  'ZkSyncMono',
  'ZkSyncCircle',
  'ZkSyncSquare',
  'ZkSyncSquareMono',
  'ZkSyncCircleMono',
  // icons/coin/busd.json
  'Busd',
  'BusdMono',
  // icons/coin/ftm.json
  'Ftm',
  'FtmMono',
  // icons/coin/mkr.json
  'Mkr',
  'MkrMono',
  // icons/defi/maker-dao.json
  'MakerDao',
  'MakerDaoMono',
  // icons/devtool/tally.json
  'Tally',
  'TallyMono',
  // icons/devtool/web3-js.json
  'Web3Js',
  'Web3JsMono',
  // icons/dex/odos.json
  'Odos',
  'OdosMono',
  // icons/dex/para-swap.json
  'ParaSwap',
  'ParaSwapMono',
  // icons/exchange/gateio.json
  'Gateio',
  'GateioMono',
  // icons/marketplace/magic-eden.json
  'MagicEdenFlat',
  'MagicEdenWordmarkFlat',
  // icons/marketplace/open-sea.json
  'OpenSeaAlt',
  // icons/marketplace/x2-y2.json
  'X2Y2',
  'X2Y2Mono',
  // icons/storage/nft-storage.json
  'NftStorage',
  'NftStorageMono',
  // icons/wallet/argent.json
  'Argent',
  'ArgentMono',
  // icons/wallet/backpack-wallet.json
  'BackpackWallet',
  'BackpackWalletMono',
  // icons/wallet/daedalus-wallet.json
  'DaedalusWallet',
  'DaedalusWalletMono',
  // icons/wallet/meta-mask.json
  'MetaMaskAlt',
  // icons/wallet/nami-wallet.json
  'NamiWallet',
  'NamiWalletMono',
  // icons/wallet/okx-wallet.json
  'OKXWallet',
  'OKXWalletMono',
  // icons/wallet/phantom-wallet.json
  'PhantomWallet',
  'PhantomWalletMono',
  'PhantomWalletCircle',
  'PhantomWalletCircleMono',
  'PhantomWalletSquare',
  'PhantomWalletSquareMono',
  'PhantomWalletSymbolMono',
  // icons/wallet/phantom.json
  'PhantomSymbolMono',
  // icons/wallet/rainbow-wallet.json
  'RainbowWallet',
  'RainbowWalletSymbol',
  'RainbowWalletCircle',
  'RainbowWalletCircleMono',
  'RainbowWalletSquare',
  'RainbowWalletSquareMono',
  'RainbowWalletMono',
  'RainbowWalletSymbolMono',
  // icons/wallet/yoroi-wallet.json
  'YoroiWallet',
  'YoroiWalletMono',
]);
